(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"MolonLabe_HTML5 Canvas_atlas_1", frames: [[0,0,844,506]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_1 = function() {
	this.initialize(ss["MolonLabe_HTML5 Canvas_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.pexelssaguiandrea618833 = function() {
	this.initialize(img.pexelssaguiandrea618833);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2200,1469);


(lib.Resting = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABqBWIgWgJQgpgTg+gDQgWgBgKAEIgVAMQgaAOgdgQQgYgOgLgeQgEgJgBgLIgBgEIAAgFQAAgMABgOQABgNAFgHQAJgMAfgCQAhgDAUgKQAQgIAFgBQAHgBAOADQAYAFAnAAQAvgBARACQAmAFAOASQAEAEAGAQQAGARAAAHIAAAHQAAAKgFAMIgCADIgCAGIgNAhQgHAUgKAGQgGADgHAAQgFAAgGgCgAgIAtQBAAGAmATIAOAHQAIACAGgCQAJgEAFgNIAJgbIgDgIQgCgGgJgBIgOABQgMAAgQgEQhYgPhXAHQgVACgJAEIgRAGIgKACQgEAGgDABQADAGAEAGQAKAPARAHQASAHARgGIANgHIAMgHQALgFATAAIASABgAA7gDIA0AHIAKAAQAFgBAHgGIATgTIAEgCIgEgLQgFgNgEgEQgLgNgcgDQgegDg8ABQgUAAgKgCIgPgDQgJgCgGABIgXAKQgMAGgUADIghAEQgMACgEAEQgGAGgBANIgBAUIAFABQAEABAJAEQAHACAJAAIARgDQAOgCAVAAIAjAAIAsgBQAWAAAeADg");
	this.shape.setTransform(16.9146,8.8217);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABuBMIgOgGQgngUhAgFQgggDgPAHIgNAHIgNAGQgQAGgSgHQgRgHgLgPQgEgFgCgGQADgCADgFIALgDIAQgGQAKgEAVgCQBWgGBYAPQARADAMAAIANAAQAJABACAGIAEAHIgKAcQgEANgKADIgGACIgHgCgABxADIg0gGQgegEgXAAIgrACIgjgBQgVAAgOADIgRADQgKAAgHgCQgIgFgFgBIgEAAIAAgUQABgNAGgGQAEgEAMgCIAigFQAUgCAMgGIAWgKQAGgBAJABIAPADQALACATAAQA8gBAeAEQAcADALAMQAEAEAGANIAEALIgEADIgTASQgHAGgGABg");
	this.shape_1.setTransform(16.7917,8.8675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,33.8,17.6);


(lib.Oh = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF6666").s().p("AAvAfIgIgEIgLgEQgNgDgSgBIgpgBIgIAAIgBAAIAAgGQABgLAGgPQAEgLAFgGQAJAFAUAFIAUAIIAHABIAIABIAbAAIgBAfQAAAGgDAGIgDgBg");
	this.shape.setTransform(6.375,7.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AACBOQgIgBgLgFQgPgGgJgGQgGgEgEgGQgJgLgCgMQgEgTAJgYQAGgPAEgGQAPgYAYgKQAZgLAaALQAPAGAEAMQADAGgBAJIAAAoIgBAUQgDARgNAUIgGAIQgGAFgKADQgJADgJAAIgFAAgAgvAmQAKASAfAJQAJADAGgBQAEAAAKgDQAIgCADgDIAFgGIAHgMIgEgCQgIgFgEgCIgIAAIgGgCIgNgBIgIgBIgugBQABAGADAFgAgugQQgGAQgBALIAAAGIABAAIAIAAIApABQASABANADIALAEIAIAEIADABQADgHAAgGIABgeIgbAAIgIgBIgHgCIgUgIQgUgEgJgGQgFAHgEAKgAAAhAQgTAHgNAQQAEACAOAEIAPAGIAQAFQAGACANAAIASAAIAAgSQAAgHgCgDQgCgGgIgEQgLgHgNAAQgJAAgJADg");
	this.shape_1.setTransform(6.3777,7.785);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHBBQgegJgLgSQgDgFgBgGIAuABIAIABIAOABIAGACIAHAAQAFACAHAFIAEACIgHAMIgFAGQgDADgHACQgLADgEAAIgCAAQgFAAgIgCgAAjgWQgNAAgGgCIgQgFIgPgGQgOgEgEgCQAOgQASgHQAYgHASALQAJAEACAGQABADAAAHIAAASg");
	this.shape_2.setTransform(6.45,7.7636);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.8,15.6);


(lib.N = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF6666").s().p("AAKALIgEgGQgGgFgCAAIgBAAQgCAAgBADIAAACIgCABIgEACQgCACAAADIg3gFIAAAAQAJgIANgFQAGgEAGAAIAIgDIABgBQAmADAmgCIACACIAIAFQAFAEADACIACAHIAAACIgvADIgLABg");
	this.shape.setTransform(12.5,8.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("ABJANQgFgNgGgEIgCgBIACAAIA8gGQAAANgEAGIgDAEIgBAAQgNABgbADIgBgDgAh1ANIgDAAQgCgHABgLIABgKIACAAQAdAFAdADQgNAGgMAKQgDACAAACIgBACg");
	this.shape_1.setTransform(13.23,7.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("Ag2BDQgegCgOgFQgYgKgHgUQgEgLACgTQACgVAFgKQALgUAegGQARgEAigCIATgDQAIgBAQACQA4AJAwAYQAKAGADAFQAEAGAAAMQAAAPgEAJQgGALgVAMIgWALQgNAEgMACQgqAHgqAAIgYgBgAhiAwQAKAGAUACQAaACAggBIAygFQAUgBAMgFQAKgDARgJIguAFIgZACQgNABgOgBIg9gCQgfgCgZgDQAGAJAMAFgAAAAXIADAFIABADIALAAIAwgEIAAgBIgDgHQgCgEgFgDIgIgGIgCgBQgnABglgCIgBAAIgIADQgGABgGADQgNAGgJAIIgBABIA3AEQABgCACgCIAEgCIACgBIgBgCQABgEADAAIABAAQADAAAGAGgAA+ADIgCABIACABQAGAFAFAMIABAEQAbgEANAAIABAAIADgEQAEgHAAgMgAh5AEQgBALACAHIADABIAcACIABgDQAAgCADgCQAMgLANgFQgdgCgdgFIgCgBIgBAKgAgkg0QgdACgPADQgaAFgKASIgCAIIABAAQBHAOBGgDIAtgCIA0gEIgBgCQgDgHgMgFQgsgVgxgJIgRgBIgfAEg");
	this.shape_2.setTransform(13.2167,6.7472);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhFA4QgUgCgKgGQgMgFgGgJQAZADAfACIA9ACQAOABANgBIAZgCIAugFQgRAJgKADQgMAFgUABIgyAFIgXAAQgTAAgQgBgAh2gQIgBAAIACgIQAKgSAagFQAPgDAdgCIAfgEIARABQAxAJAsAVQAMAFADAHIABACIg0AEIgtACIgYABQg6AAg7gMg");
	this.shape_3.setTransform(13.325,6.7281);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,26.5,13.5);


(lib.M = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABDArIg2gEQgLAAgVgEIgigEQgJgBgBgEQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAgBQADgCAGABIB/ANIAEABQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBABQAAAAAAAAQgBABAAAAQAAABgBAAQgCABgDAAIgEAAgACCAOIgGgDIgngXQgUgMgLgDQgNgDgQABQgTAAgIAFIgNAFQgFAAgHgEIgNgIQgIgCgMAEIgTAKQgHADgRAEQgQAEgIAEQgEACgCAAQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAAAgBQgBgEACgCQADgDAIgBQAbgGAZgMQAOgHAHgBQALgBAMAHQAJAGADAAIANgFQAIgFASAAQAUgBANAEQANAEAXANIAnAWQAJAFgDAFQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIgCgBgAA5ALQgLgEgPgCQgagDgXABIgXACIgXAAQgHAAgBgEQgBgCAEgCIAHgBIATgDQAMgCAIABIAGAAIAGgBIADACIADAAQAiAAAhAIIAFADQADACgBADQgBAEgEAAIgHgCg");
	this.shape.setTransform(13.7325,4.315);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,27.5,8.7);


(lib.L = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhTBOQgUgCgLgDQgRgFgJgLQgGgHgDgIIACAAQAIAAALAEIAUAFQAdAIA3ACIA7ABQAoABAegEQAQgDALgEIgDACQgYAOgSAGQgTAGgbACIgdABQglAAg6gFgABRgGIiBgDQgpgBgUgEQgTgEgGgKIgBgBQAKgSAKgHQAHgFARgHIARgKQAIgEAOAAIAYAAIARgBIAQgBIAfAFIA0APQAaAHAQAKQAMAIAIALIgMAHQgJAGgHADQgMAFgVAAIgIgBg");
	this.shape.setTransform(16.325,9.2617);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6666").s().p("AAwAWQgBgDgFgBQgGgBgCgCQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAAAIgCgEQgCgDgDgBQgDgCgCAEQgCADACADIAFAJIAHAEIgDAAQgcAAgegCIgDAAQADAAADgDIAFgHIADgEIACgFQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQgEgDgEADIgGAIIgBABQAAACgDACQgEADgBACQAAAAAAABQAAAAABABQAAABAAAAQABABAAAAIACABQgZgBgOgCIgEAAIAAgBIAAgDIABgDQAEgDgBgEQADgBADgFQAAgDADgDIAEgDQAFgFAHgDIAHgEIADgDIBiACIADADIAHAEQADABAEAIQAFAMAAAPIABADIgiACIABgEg");
	this.shape_1.setTransform(16.3,11.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgUBcIhFgFQgYgCgNgFQgQgHgLgPQgKgOgBgSQgBgVAPgfQALgVAIgIQAJgJATgLQAXgMAIgCQAKgCANgBIAYAAQAYgBALABQASACASAGQAVAEASAGQAeAJAQAKQARAKAJAOQAEAAABADQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAIACAGQAEANgCAQQgCAUgHAMQgIAKgTAMQgXANgUAGQgNAEgZADQgTACgWAAIgbgBgAiOA5QAJAKARAFQALADAUACQBTAHApgDQAbgBATgGQASgGAYgPIADgCQgLAEgQADQgeAEgogBIg7gBQg3gCgdgIIgUgFQgLgDgIgBIgCAAQADAJAGAHgAAWAeQADAAABAEIADADQAAABAAAAQAAABABAAQAAABAAAAQABABABAAQACACAGAAQAFABABAEIgBADIAhgBIAAgDQAAgPgGgOQgDgHgDgCIgHgDIgDgDIhigDIgDAEIgIADQgGADgGAGIgDADQgDADAAACQgDAHgDABQAAAEgDADIgCADIAAACIAAACIAFAAQAOACAZABIgCgBQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQABgCADgDQAEgDAAgCIAAAAIAGgJQAFgDADADQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABIgCAEIgDAFIgFAHQgDADgDAAIADAAQAdACAdAAIACAAIgGgEIgGgKQgCgCACgDQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIACABgABPAJQAKATgBAUIAAABIAQgCQASgDAIgEQAJgGADAFIABACIADgEQAGgHADgSQACgMgCgKIgDgHQgYAQgPACQgHACgWAAIgJAAgAhcAsQgBgDACgDQABgDACgBIACgHQADgCACgEIACgFIADgEIADgCIAEgFIADgCIAFgDIgcgBQgTgBgLgDQgPgEgIgJQgJASgCAPQgBAIABAIQAGgBAQAEIAnAKIAAAAgAg2hRQgOAAgIAEIgRALQgRAHgHAFQgKAGgKATIABABQAGAKATAEQAUAEApABICBADQAbABAOgGQAHgCAJgHIAMgHQgIgKgMgJQgQgKgagHIg0gOIgfgFIgQAAIgRABIgOAAIgKAAg");
	this.shape_2.setTransform(16.5423,9.3031);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("ABXAhQABgUgJgSIgFgGIAJAAQAWAAAIgCQAOgDAZgQIACAHQACAKgBANQgDARgGAHIgDAEIgCgCQgDgFgJAGQgHAEgTADIgQACIAAgBgAiEATQgPgEgHABQgBgIABgIQACgOAJgTQAJAJAPAEQAKADAUABIAcABIgFAEIgEACIgEAFIgDACIgCADIgDAFQgBAEgDACIgDAHQgCABgBADQgBADABADIgogKg");
	this.shape_3.setTransform(16.5821,10.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,33.1,18.6);


(lib.Ah = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("ACBApQgsgSg/gIQgTgChcgGQgigBgQAFIAAgBQAAgRALgPQAHgJALgJIACAAIANAEQAMAEASACQBoAPA3gHIAVgDIAFgDQAJALAHANQAEAJgBAGIgEALIgEAOIgBAFg");
	this.shape.setTransform(14.958,9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AA+BXQgcgCgXgFQgegFgKABQgSAEgJABQgLABgRgEQgUgFgLgGQgSgLgJgUQgKgUAGgTQAEgPAOgRQAQgRAVgMQANgIAWgHQAMgEAJgCQALgBALABQALABATAGIASABIASABQAcAEAYASQAXARAPAaQAGALAAAHQABAIgEALQgIAegLAMQgSATgnAAIgIAAgAAJBGQAeAFAiABQARAAAKgDQAMgEAIgJIAFgFIgBgBQg0gXhdgGQgzgEgoAAQgOAAgFACIgFACQAEAQAPALQAQANAaAFQALABAKgBIAWgFIAEAAQAMAAAZAFgAhZALQBdAFASADQA/AHAtATIAAAAIACgGIADgOIAFgLQABgFgFgKQgGgNgJgLIgGADIgUADQg3AHhpgPQgRgBgNgEIgNgEIgCgBQgLAJgGAJQgMAQABAQIAAABQALgEAWAAIAQABgAhkgtQAMAFAYADQA3AIAhACQAxACAngHIACgBIgMgLQgXgSgbgDIgZgCIglgGIgKgBQgoAAgoAdg");
	this.shape_1.setTransform(14.9273,8.6962);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAPBFQgegGgLABIgWAFQgKABgLgBQgagFgQgNQgOgLgFgQIAFgCQAFgCAOAAQAoAAA0AEQBdAGA0AXIAAABIgFAFQgIAJgMAEQgKADgRAAQgigBgegFgAAegcQghgCg3gIQgXgDgNgFQAtggAtAEIAlAGIAaACQAaADAXASIANALIgDABQgdAGgjAAIgYgBg");
	this.shape_2.setTransform(14.3,8.7531);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,29.9,17.4);


(lib.Ae_ay = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("ABuAOQgNgHgaAAIiYgHIgyAAIgBAAQAAgHAEgGQAYAGAWACIAiACIB7gEQAqgDAQgFQACAJgIAKQgGAGgHAGIgEgCg");
	this.shape.setTransform(14.3784,6.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhSAuQgTgBgIgGQgOgHgEgPIgBgEIABAAQBkACBmAGQAXACAJAEQgNAGgQADQgOADguADIgyADIgfABIgTAAgAg7gKIgfgCIgbgGQAJgKASgHQARgHANgCQAJgBAaAAIAjAAQAMAAAGADIAHADIAKABQAfAAAtAPIAIADQgQAEgdADQgsADhDAAIggAAg");
	this.shape_1.setTransform(14,5.6821);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AhOA5QgcgBgPgJQgTgNgCgWQgDgVAQgQQAIgKASgHQAVgJANgCQARgEAjABQAiABARADIAdAFQAfAGAXAHQAQAFAFAGQAJAKgFANQgCAKgLALQgVAUgmAHIghADIghABQgyAFgbAAIgFAAgAiDARQAEAPAOAHQAJAGASABQAVABAegCIAxgDQAugDAOgDQAQgDANgGQgJgEgXgCQhlgGhlgCIgBAAIABAEgAiEADIABAAIAyABICYAHQAaABANAGIAEACQAHgFAGgHQAIgKgCgJQgQAFgqADIh7ADIgigBQgWgBgYgHQgEAGAAAGgAg/gsQgNACgSAHQgSAHgJAKIAbAGIAgACQBZABA1gEQAdgDAQgEIgIgDQgsgPgfAAIgLgBIgHgDQgFgDgNAAIgjAAQgaAAgIABg");
	this.shape_2.setTransform(14.3826,5.691);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,28.8,11.4);


// stage content:
(lib.MolonLabe_HTML5Canvas = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [9];
	// timeline functions:
	this.frame_9 = function() {
		playSound("MySong256wav");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(51));

	// Mouth
	this.instance = new lib.Resting("synched",0);
	this.instance.setTransform(448.1,353.8,1,1,0,0,0,16.9,8.8);

	this.instance_1 = new lib.M("synched",0);
	this.instance_1.setTransform(445.85,356.7,1,1,0,0,0,13.7,4.3);

	this.instance_2 = new lib.Oh("synched",0);
	this.instance_2.setTransform(445.85,357.15,1,1,0,0,0,6.4,7.8);

	this.instance_3 = new lib.L("synched",0);
	this.instance_3.setTransform(445.9,357.2,1,1,0,0,0,16.6,9.3);

	this.instance_4 = new lib.Ah("synched",0);
	this.instance_4.setTransform(445.45,357.15,1,1,0,0,0,14.9,8.7);

	this.instance_5 = new lib.N("synched",0);
	this.instance_5.setTransform(448.1,356.65,1,1,0,0,0,13.2,6.8);

	this.instance_6 = new lib.Ae_ay("synched",0);
	this.instance_6.setTransform(446.9,354.6,1,1,0,0,0,14.3,5.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance,p:{regX:16.9,x:448.1}}]}).to({state:[{t:this.instance_1,p:{x:445.85,y:356.7}}]},9).to({state:[{t:this.instance_2}]},3).to({state:[{t:this.instance_2},{t:this.instance_3,p:{x:445.9,y:357.2}}]},3).to({state:[{t:this.instance_2},{t:this.instance_4,p:{x:445.45,y:357.15}}]},1).to({state:[{t:this.instance_5}]},2).to({state:[{t:this.instance_5},{t:this.instance_3,p:{x:448,y:356.6}}]},2).to({state:[{t:this.instance_5},{t:this.instance_4,p:{x:447.45,y:355.75}}]},1).to({state:[{t:this.instance_1,p:{x:446.6,y:355.95}}]},2).to({state:[{t:this.instance_6}]},4).to({state:[{t:this.instance_6}]},6).to({state:[{t:this.instance,p:{regX:18,x:449.2}}]},13).wait(14));

	// Head
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AieAAQAAAHgBAGQgDALgJAJQgOANgTAAQgUAAgNgNQgOgOAAgTQAAgSAOgOQADgDAEgDQAIgFAJgCQAEAAAFAAQACAAABAAQAPABALAJQACABACACQAEAEADAFQAGAKAAANgAC5gpQAGgDAFgBQAFAAAEAAQARAAAMAKQACABACACQAEAEADAFQAHAKAAANQAAATgOAOQgNANgUAAQgTAAgOgNQgNgOAAgTQAAgSANgO");
	this.shape.setTransform(448.975,301.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC99").s().p("ABnJIQgigGgQgNQgJgHgQgVQgPgVAEgMIAHgOQADgJgEgEIAEgIQAGgNgFgYIgDgOQAAgMgBgGQgBgDgDgBQgDgBgCADQgGAFAAAQIABAsQAAALgBAGIgEAJQgFALAAAFIACABQgHAdgqATQgyAVg2gDQhBgDgsgmQgFgFgDgBQAWgyAMghQAkhfAOhTQAJg2AGhiQAMjLACh7IAAgbQgBgPgEgKQgFgPgMgMQgHgIgQgLQhzhOgmggQhShGgwhTQAWgVAtAPQAfALCSBKQAYAMAXAKIgEgBQgPgBgIACIgTAJIgMAEIgHACQgJADgGAGIgNAJIgUAQQAKAGAMgBIgBAFQABAEAEAAIAIAAIAJADQAFACADAAQAGAAAKgJQAKgJALgEIAKgFQAFgFgEgFQAZgBAkADQA2AGAVAAIADAAIAJgBQAdDIBBCwQgJADgIAAIgJgBQgDgBgFgFQgSgSgGgLQgFgHgEgMIgCgLIgBgUIAAgkIABgTIADgKIABgSIAAgkQAAgTgDgIQgEgCgCAFIgBAHIAAAxQAAAMgCAGIgCAIIgBAOIAAAKIgBAAQgEABgIAFQgYAPgKAOQgQAUADAWQADAWAXAQQAPALAdAGQAZAGANgHQAGADAGABQALAAANgEIABACIADgEIAGgCIAEgBQAIADAMAAIAiAAQAJABAGgBQAHgBALgGQAZgOAHgWQAEgMgDgNQgDgNgKgHQgHgGgRgFQgPgEgHgEIABgHIACgHQACgFAAgMQAAgSgBgJIgCgLQgFgQgLgNQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBAEAEAFIAGAIQABAEAAAIIAEAJIABAKIgBALIABAHQAAAEgBADIgEAJQgBAFABAKIAAAAQgBAFgEAJIgXAwQgFALgFAFQgFAFgJAEQAQghAJg3QALhUAJgoQAMgwAEgXQAJgqgDgfIAjgFQgGAFgEAHQAHAIATgFIATgFQALADALAAQgOANAAAUQAAATAOAOQANANAUAAQATAAAOgNQANgOAAgTQAAgOgGgKIgHgJIgEgEQgNgKgQAAIgJABIgLAEIgGgBQAigHAjgCQAWgBAPACQABADADADQAEAEAHAEQAVALALABIAMABQAPABAQAHQAFACACgBQACgCABgGQADgDAAgCQABgCgCgDQgGgKgJgHQADgDgBgGQgBgFgDgDIgQgMIgJgHIgHgBIgKAAIgjgBQA9gSA9gZQAOgFAGAGQAHAGABARQACAfgNAlQgSAxgjAiQghAfgoAMQgcAHgOAFQgYAIgNARQgTAXgJAvQgKA1ACBRIAECHQAAA4gHBuQgDA3AEAeQAEAkATA9IAaBUIgKANQgFAIgKAGIgSAJIglAVQgWAMgRAEQgIACgLAAQgQAAgVgEgAiumsQgJACgHAFIgIAGQgNANAAAUQAAATANAOQAOANATAAQAUAAANgNQAJgJADgMQACgGAAgGQAAgOgHgKIgHgJIgEgEQgLgIgOgCIgEAAIgJABgAhMhMQgRgOgCgRQAAgJAFgLQAKgVAkgVIAAAzIACAIIAHARIANATQAHAJAFABIADAGIgEAAIgLABQgeAAgYgTgABSg+IgNgBIAEgDQAHgHAIgQIARgjQAHgPACgJQAHAEAJACQATAGAGAHQANANgFATQgEARgRAKQgMAGgRACIgNAAIgSAAgAFwmhIgDgCIgDgBIgFgBIgCgBIgBgCIAGACIAIACIAIACIgFABIgDAAg");
	this.shape_1.setTransform(445.0133,339.5545);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["#FF0000","#000000"],[0,1],28,-32,0,28,-32,94.3).s().p("ABbIOQgFgDgLgFIgKgFIgKgJIgIgKIgMgPQgFgFgLgGIgCgBIgOgPQgMgLgKgDQgLgCgNAEQgHACgNAIQgXABgNAGIgcAOIgOAHQgGAEgHAIIgOAQIgDgPIgsi5QgahvgKhKIgKhhQgVkEgLjvIgDg2QD6gKD1A0QAaAEAQAIIAMAHQAWARALAnQAKAlAABDQABBYgPA3QgHAbgRAmIgcA/QgcBBgWBfQgLAvgXCAIgoDoIgEACIAAAAQgEAAgHgGg");
	this.shape_2.setTransform(448.0031,150.0456);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FFFFFF","#000000"],[0,1],49.1,-29.8,-124.8,107.7).s().p("AEyQGQgMgCgHgIQgHgIgGgWIgUhDIACgCQAGgIgFgEQgDAAgEABIghhwIgNguQgFgagCgWQgCgYAEgiIAGg7QAFg2gEhxQgFhwAGg4QAGhEAYgdQANgPAUgIIAlgKQA7gRAngwQAWgbANgiQAOgkADgnQABgVgGgLQgKgRgcALQhvAqhyAZIgEAAQgFgBgCACIgCACIggAGIgCAAIgDABIgPADIgCAAIgEABIgjAGIgkDdQgJA0gGAaQgKAqgNAdIgBABQhAi0gfjGQACgCAAgEQgBgFgDgEQgFgGgLgDQgggKgqABIgPAAQgrgQgygaQiKhIg+gJQgMgCgJAFQgMAGgBANQAAANALAQQAxBJBNBAQAvAnBfA/QAPALAHAHQAMALAGAOQAHAPABAXQABAOgCAaIgOEPIgGBgQgFA1gHApQgPBRgjBbQgNAggWAwIgBADIgkBMIgcgjQhniAhTiYQhBh1g0iFQgMggABgSQAAgNAIgXIBJjQQAHgWADgNQAFgUAAgRQgBgcgRgeQgVgggKgRQgig7gIhbQgGhOAOhaQASh0ApheQAZg4AfgqQAZgjAdgZQAUgRAlgYQAqgbAQgMQAhgaA+g7QAygsBDgoIAEgCIABAGQADgEABgGQApgYBGgkIAIgBIAqAAQAGAHAPAKIAEADIAXAWIADAEQAFAIAFADQAEAEAKAEIABABQARANARAMIgBAGIACgFQAdAUAgAPQAgAQBBAbQA6AZAjAeQAlAgAoA7QAYAiAtBHIAoA7IALARQAdAsAQAlQAoBbAEB0QADBwggBlQgHAXADAKQACAJAPALQAoAdARAoQAPAkABA0QAABKggBoIg2CtIgNBGQgIAugHAZQgPA9gcA5QgQAfgSAdQgsBGhFBFQgXAXgQAKQgTALgQAAIgJgBg");
	this.shape_3.setTransform(448.4494,299.1694);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ACsAhQgNgNAAgUQAAgSANgOIAOgBQAFgBACgEQgCgCgGgBIALgDIAJgBQARAAAMAKIAEADIAHAJQAHAKAAANQAAAUgOANQgNAOgUAAQgTAAgOgOgAjtAhQgOgNAAgUQAAgSAOgOIAHgGQAIgFAJgBIAJgBIADAAQAPABALAJIAEADIAHAJQAGAKAAANQAAAHgBAFQgDAMgJAJQgOAOgTAAQgUAAgNgOg");
	this.shape_4.setTransform(448.975,301.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AEzYDQgOgBgIgJQgIgJgHgYIgWhGQgHAIgKAIQgLAJgbAQQguAbgcADQgTADgigHQglgGgSgOQgQgNgUglQgTAWgaAOQgJAFgfALIgVAGQgFABgTAAQggAAgQgCQg7gIgtgmIggBHQgFALgFABQgFABgHgKQhyibhDhwIgVgkQhOiIgviFQgKgcAAgSQAAgQAKgdIBIjOQAHgUACgLQAEgSAAgPQgBgZgPgcIgcgtQgkg7gIhaQgIhNAMhaQARiCAxhpQAag5AggrQAfgqAlgcQAQgNAjgVQAigVARgNQAQgOAcgbQAfggAMgKQAcgYAwgfIAxgeIg0jjQgXhlgGgnQgJg7gGhkIgjn4QgBgSAGgFQAFgFAPAAQCdADBOAFQCCAJBmAWQAuALAVAPIACACQAiAaAOA4QAaBoguCTQgLAighBWQgdBMgNAtQgRA+gZCpQgRB3gYBMQAFAAABAFQAAADgCAFQgEAEgEACQAXAOAaAOQAwAYBhAsQAxAZAdAeQARATAgAuIBVCAIAaAmQAZAnAOAZQAhA7AQA5QAXBQgDBgQgEBXgYBYQgHAYAEALQADAJAOAJQAiAVASArQAQAkABA1QACBLgeBkQgRA5gkBxQgGAYgOBIQgMA9gKAiQgQAygYAwQgPAbgRAcQgmA6g8BAQgbAegTAOQgaARgWAAIgFAAgAEBV8QAFAEgGAIIgCACIAUBDQAGAWAHAIQAHAIAMACQAUAEAYgOQAQgKAXgXQBFhFAshGQATgdAPgfQAcg5APg9QAHgZAIguIANhGIA2itQAghoAAhKQgBg0gPgkQgRgogogdQgPgLgCgJQgDgLAHgXQAghlgDhwQgEh0gohbQgQglgdgrIgLgRIgog7QgthHgYgiQgog7glggQgjgeg6gZQhBgbgggQQgfgPgegVIgCAGIABgGQgRgMgRgNIgBgBQgKgEgEgEQgFgDgFgIIgDgEIgXgWIgEgDQgPgKgGgHIgqAAIgIABQhGAkgpAYQgBAGgDAEIgBgHIgEADQhDAogyAsQg+A7ghAaQgQAMgqAbQglAYgUARQgdAZgZAjQgfAqgZA4QgpBdgSB0QgOBaAGBOQAIBbAiA7QAKARAVAhQARAeABAcQAAARgFAUQgDANgHAWIhJDQQgIAXAAANQgBASAMAgQA1CEBAB2QBTCYBnCAIAcAjIAkhMIABgDQAWgwANggQAjhbAPhRQAHgpAFg1IAGhgIAOkPQACgagBgOQgBgXgHgPQgGgOgMgLQgHgHgPgLQhfg/gvgoQhNhAgxhJQgLgQAAgNQABgNAMgGQAJgFAMACQA+AJCKBIQAyAaArAQIAPAAQAqgBAgAKQALADAFAGQADAEABAFQAAADgCADQAgDHA/CzIABAAQANgdAKgqQAGgaAJg0IAkjeIAjgGIAEgBIACAAIAPgDIADgBIACAAIAggGIACgCQACgCAFABIAEAAQBygZBvgqQAcgLAKARQAGALgBAVQgDAngOAkQgNAjgWAbQgnAwg7ARIglAKQgUAIgNAPQgYAdgGBEQgGA4AFBwQAEBxgFA2IgGA7QgEAiACAYQACAWAFAaIANAuIAhBwQADgBADAAIABAAgAgNUPQADABABADQABAGAAAMIADAOQAFAYgGANIgEAHQAEAFgDAJIgHAOQgEAMAPAVQAPAVAJAHQAQANAiAGQAjAGAVgEQARgEAWgMIAlgVIASgJQAKgGAFgIIAKgNIgahUQgTg9gEgkQgEgeADg3QAHhuAAg4IgEiIQgChRAKg1QAJgvATgXQANgRAYgIQAOgFAcgHQAogMAhgfQAjgiASgxQANglgCgfQgBgRgHgGQgGgGgOAFQg9AZg9ASIAjABIAKAAIAHABIAJAHIAQAMQADADABAFQABAGgDADQAJAHAGAKQACADgBACQAAACgDADQgBAGgCACQgCABgFgCQgQgHgPgBIgMgBQgLgBgVgLQgHgEgEgEQgDgDgBgDQgQgCgVABQgjACgiAHIAGAAQAFACADACQgCAEgGABIgNABQgLAAgLgEIgTAGQgTAFgHgIQAEgHAGgFIgjAFQADAfgJAqQgEAXgMAwQgJAogLBUQgJA2gQAiQAJgEAFgFQAFgFAFgLIAXgwQAEgJABgFIAAAAQgBgKABgFIAEgJQABgDAAgEIgBgHIABgLIgBgKIgEgJQAAgIgBgEIgGgIQgEgFABgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQALANAFAQIACALQABAJAAASQAAAMgCAFIgCAHIgBAHQAHADAPAFQARAFAHAGQAKAHADANQADANgEAMQgHAWgZAOQgLAGgHABQgGABgJgBIgiAAQgNAAgIgEIgDACIgGACIgDAEIgBgDQgMAFgLAAQgHgBgGgDQgNAHgZgGQgdgGgPgLQgXgQgDgWQgDgWAQgUQAKgOAYgPQAIgFAEgBIABAAIAAgKIABgOIACgIQACgGAAgMIAAgxIABgHQACgFAEACQADAIAAATIAAAkIgBASIgDAKIgBATIAAAkIABAUIACALQAEAMAFAHQAGALATASQAFAFADABIAJABQAIAAAIgDQhBiwgdjJIgJACIgDAAQgVAAg2gGQgkgDgaABQAFAEgFAGIgKAFQgLAEgKAJQgKAJgGAAQgDAAgFgCIgJgDIgIAAQgEAAgBgEIABgFQgMABgKgGIAUgQIANgKQAGgFAJgDIAHgCIAMgEIATgJQAIgCAPABIAEAAQgXgJgYgMQiShKgfgLQgtgPgWAVQAwBTBSBGQAmAgBzBOQAQALAHAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gMDMQgGBigJA2QgOBTgkBfQgMAhgXAyQAEABAFAFQAsAmBBADQA2ADAygVQApgTAJgdIgCgBQAAgFAFgLIAEgJQABgGAAgLIgBgsQAAgQAGgFQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAIABAAgAh8MDQgFALAAAJQACARARAOQAcAWAlgEIAEAAIgDgGQgFgBgHgJIgNgTIgHgRIgCgIIAAgzQgkAUgKAWgABHMGIgRAjQgIAQgHAHIgEADIANABQAUABALgBQARgCAMgGQARgKAEgRQAFgTgNgNQgGgHgTgGQgKgDgGgDQgCAJgHAPgAFBHcIACABIAFABIADABIADACQADABAFgCIgIgCIgIgCIgGgCIABACgAgXotQAKACANAMIANAOIACACQALAGAFAEIAMAQIAIAKIAKAIIAKAGQALAEAFAEQAIAGADgBIAEgCIAojnQAXiAALgvQAWhgAchCIAcg/QARglAHgbQAPg3gBhYQAAhDgKglQgLgngWgRIgMgHQgQgIgagFQj1gzj6AKIADA2QALDvAVEEIAKBhQAKBLAaBvIAsC4IACAQIAPgRQAHgHAGgFIAOgGIAcgOQANgGAWgCQAOgHAHgCQAJgDAHAAIAIABgAh8oEQgTAKgKAJIAxgdIgUAKg");
	this.shape_5.setTransform(448.4312,249.6845);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1,1,1).p("AieAAQAAAGgBAHQgDALgJAJQgOANgTAAQgUAAgNgNQgOgOAAgTQAAgSAOgOQADgDAEgDQAIgFAJgCQAEAAAFAAQACAAABAAQAPAAALAKQACABACACQAEAEADAFQAGAKAAANgAC6gpQAFgCAFgCQAFAAAEAAQARAAAMAKQACABACACQAEAEADAFQAHAKAAANQAAATgOAOQgNANgUAAQgTAAgOgNQgNgOAAgTQAAgSANgO");
	this.shape_6.setTransform(448.475,300.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#FFFFFF","#000000"],[0,1],49.1,-29.8,-124.8,107.7).s().p("AEyQGQgMgCgHgIQgHgIgGgWIgUhDIACgCQAGgIgFgEQgDAAgDABIgihwIgNguQgFgagCgWQgCgYAEgiIAGg7QAFg2gEhxQgFhwAGg4QAGhEAYgdQANgPAUgIIAlgKQA7gRAngwQAWgbANgiQAOgkADgnQABgVgGgLQgKgRgcALQhvAqhxAZIgFAAQgFgBgCACIgBACIggAGIgDAAIgCABIgQADIgCAAIgEABIgjAGIgkDdQgJA0gGAaQgKAqgNAdIAAABQhAi0gfjGQABgDAAgDQgBgFgDgEQgFgGgLgDQgggKgqABIgPAAQgqgQgzgaQiKhIg+gJQgMgCgJAFQgMAGgBANQAAANALAQQAxBJBNBAQAvAnBfA/QAPALAHAHQAMALAGAOQAHAPABAXQABAOgCAaIgOEPIgGBgQgFA1gHApQgPBRgjBbQgNAggWAwIgBADIgkBMIgcgjQhniAhTiYQhAh1g1iFQgMggABgSQAAgNAIgXIBJjQQAHgWADgNQAFgUAAgRQgBgcgRgeQgVgggKgRQgig7gIhbQgGhOAOhaQASh0ApheQAZg4AfgqQAZgjAdgZQAUgRAlgYQAqgbAQgMQAhgaA+g7QAygsBDgoIAEgCIABAGQADgEABgGQApgYBGgkIAIgBIAqAAQAGAHAPAKIAEADIAYAWIACAEQAFAIAFADQAEAEAKAEIACABIAhAZIgBAGIACgFQAeAUAfAPQAgAQBBAbQA6AZAjAeQAlAgAoA7QAYAiAtBHIAoA7IALARQAdAsAQAlQAoBbAEB0QADBwggBlQgHAXADAKQACAJAPALQAoAdARAoQAPAkABA0QAABKggBoIg2CtIgNBGQgIAugHAZQgPA9gcA5QgPAfgTAdQgsBGhFBFQgXAXgQAKQgTALgQAAIgJgBg");
	this.shape_7.setTransform(447.9494,298.1694);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.rf(["#FF0000","#000000"],[0,1],28,-32,0,28,-32,94.3).s().p("ABbIOQgFgDgLgFIgKgFIgKgIIgIgLIgMgPQgFgFgLgGIgCgBIgOgPQgMgLgKgDQgLgCgNAEIgUAKQgXABgNAGQgSAKgKAEIgOAHQgGAEgHAIIgOAQIgDgPIgsi5QgahvgKhKIgKhhQgVkEgLjvIgDg2QD6gKD1A0QAaAEAQAIQAHADAFAEQAWARALAnQAKAlAABDQABBYgPA3QgHAbgRAmIgcA/QgcBBgWBfQgLAvgXCAIgoDoIgEACIAAAAQgEAAgHgGg");
	this.shape_8.setTransform(447.5031,149.0456);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ACsAhQgNgNAAgUQAAgSANgOIAOgBQAFgBACgEQgCgCgFgBQAFgCAFgBIAJgCQARAAAMALIAEADIAHAJQAHAKAAANQAAAUgOANQgNAOgUAAQgTAAgOgOgAjtAhQgOgNAAgUQAAgSAOgOIAHgGQAIgFAJgBIAJgCIADAAQAPABALAKIAEADIAHAJQAGAKAAANQAAAHgBAGQgDALgJAJQgOAOgTAAQgUAAgNgOg");
	this.shape_9.setTransform(448.475,300.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFCC99").s().p("ABnJIQgigGgQgNQgJgHgQgVQgPgVAEgMIAHgOQADgJgEgEIAEgIQAGgNgFgYIgDgOQAAgMgBgGQgBgDgDgBQgDgBgCADQgGAFAAAQIABAsQAAALgBAGIgEAJQgFALAAAFIACABQgIAdgpATQgyAVg2gDQhBgDgsgmQgFgFgDgBQAWgyAMghQAkhfAOhTQAJg2AGhiQAMjLACh7IAAgbQgBgPgEgKQgFgPgMgMQgHgIgQgLQhzhOgmggQhShGgwhTQAWgVAtAPQAfALCSBKIAvAWIgEgBQgPgBgIACIgTAJIgMAEIgHACQgJADgGAGIgNAJIgUAQQAKAGAMgBIgBAFQABAEAEAAIAIAAIAJADQAFACADAAQAGAAAKgJQAKgJALgEIAKgFQAFgGgEgEQAZgBAkADQA2AGAVAAIADAAIAJgBQAdDIBBCwQgJADgIAAIgJgBQgDgBgFgFQgSgSgGgLQgFgHgEgMIgCgLIgBgUIAAgkIABgTIADgKIABgSIAAgkQAAgTgDgIQgEgCgCAFIgBAHIAAAxQAAAMgCAGIgCAIIgBAOIAAAKIgBAAQgEABgIAFQgYAPgKAOQgQAUADAWQADAWAXAQQAPALAdAGQAZAGANgHQAFADAHABQALAAANgEIABACIADgEIAGgCIAEgBQAHADANAAIAiAAQAJABAGgBQAHgBALgGQAZgOAHgWQAEgMgDgNQgDgNgKgHQgHgGgRgFIgWgIIABgHIACgHQACgFAAgMQAAgSgBgJIgCgLQgFgQgLgNQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBAEAEAFIAGAIQABAEAAAIIAEAJIABAKIgBALIABAHQAAAEgBADIgEAJQgBAFABAKIAAAAQgBAFgEAJIgXAwQgFALgFAFQgFAFgJAEQAQgiAJg2QALhUAJgoQAMgwAEgXQAJgqgDgfIAjgFQgGAFgEAHQAHAIATgFIATgFQALADALAAQgOANAAAUQAAATAOAOQANANAUAAQATAAAOgNQANgOAAgTQAAgOgGgKIgHgJIgEgEQgNgKgQAAIgJABQgGABgFADIgGgBQAigHAjgCQAVgBAQACQABADADADQAEAEAHAEQAVALALABIAMABQAPABAQAHQAFACACgBQACgCABgGQADgDAAgCQABgCgCgDQgGgKgJgHQADgDgBgGQgBgFgDgDIgQgMIgJgHIgHgBIgKAAIgjgBQA9gSA9gZQAOgFAGAGQAHAGABARQACAfgNAlQgSAxgjAiQghAfgoAMQgcAHgOAFQgYAIgNARQgTAXgJAvQgKA1ACBRIAECHQAAA4gHBuQgDA3AEAeQAEAkATA9IAaBUIgKANQgFAIgKAGIgSAJIglAVQgWAMgRAEQgIACgLAAQgQAAgVgEgAiumsQgJACgHAFIgIAGQgNANAAAUQAAATANAOQAOANATAAQAUAAANgNQAJgJADgMQACgGAAgGQAAgOgHgKIgHgJIgEgEQgLgJgOgBIgEAAIgJABgAhMhMQgRgOgCgRQAAgJAFgLQAKgVAkgVIAAAzIACAIIAHARIANATQAHAJAFABIADAGIgEAAIgLABQgeAAgYgTgABSg+IgNgBIAEgDQAHgHAIgQIARgjQAHgPACgJIAQAGQATAGAGAHQANANgFATQgEARgRAKQgMAGgRACIgNAAIgSAAgAFwmhIgDgCIgDgBIgFgBIgCgBIgBgCIAGACIAIACIAIACIgFABIgDAAg");
	this.shape_10.setTransform(444.5133,338.5545);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AEzYDQgOgBgIgJQgIgJgHgYIgWhGQgHAIgKAIQgLAJgbAQQguAbgcADQgTADgigHQglgGgSgOQgQgNgUglQgTAWgaAOQgJAFgfALIgVAGQgFABgTAAQggAAgQgCQg7gIgtgmIggBHQgFALgFABQgFABgHgKQhyibhDhwIgVgkQhOiIgviFQgKgcAAgSQAAgQAKgdIBIjOQAHgUACgLQAEgSAAgPQgBgZgPgcIgcgtQgkg7gIhaQgIhNAMhaQARiCAxhpQAag5AggrQAfgqAlgcQAQgNAjgVQAigVARgNQAQgOAcgbQAfggAMgKQAcgYAwgfIAygeIg1jjQgXhlgGgnQgJg7gGhkIgjn4QgBgSAGgFQAFgFAPAAQCdADBOAFQCCAJBmAWQAuALAVAPIACACQAiAaAOA4QAaBoguCTQgLAighBWQgdBMgNAtQgRA+gZCpQgRB3gXBMQAEAAABAFQAAADgCAFQgEAEgEACQAXAOAaAOQAwAYBhAsQAxAZAdAeQARATAgAuIBVCAIAaAmQAZAnAOAZQAhA7AQA5QAXBQgDBgQgEBXgYBYQgHAYAEALQADAJAOAJQAiAVASArQAQAkABA1QACBLgeBkQgRA5gkBxQgGAYgOBIQgMA9gKAiQgPAygZAwQgPAcgRAbQgmA6g8BAQgbAegTAOQgaARgWAAIgFAAgAEAWIIgCACIAUBDQAGAWAHAIQAHAIAMACQAUAEAYgOQAQgKAXgXQBFhFAshGQATgdAPgfQAcg5APg9QAHgZAIguIANhGIA2itQAghoAAhKQgBg0gPgkQgRgogogdQgPgLgCgJQgDgLAHgXQAghlgDhwQgEh0gohbQgQglgdgrIgLgRIgog7QgthHgYgiQgog7glggQgjgeg6gZQhBgbgggQQgfgPgegUIgCAFIABgGIghgZIgCgBQgKgEgEgEQgFgDgFgIIgCgEIgYgWIgEgDQgPgKgGgHIgqAAIgIABQhGAkgpAYQgBAGgDAEIgBgGIgEACQhDAogyAsQg+A7ghAaQgQAMgqAbQglAYgUARQgdAZgZAjQgfAqgZA4QgpBdgSB0QgOBaAGBOQAIBbAiA7QAKARAVAhQARAeABAcQAAARgFAUQgDANgHAWIhJDQQgIAXAAANQgBASAMAgQA1CFBAB1QBTCYBnCAIAcAjIAkhMIABgDQAWgwANggQAjhbAPhRQAHgpAFg1IAGhgIAOkPQACgagBgOQgBgXgHgPQgGgOgMgLQgHgHgPgLQhfg/gvgoQhNhAgxhJQgLgQAAgNQABgNAMgGQAJgFAMACQA+AJCKBIQAzAaAqAQIAPAAQAqgBAgAKQALADAFAGQADAEABAFQAAADgBADQAfDHBAC0IAAgBQANgdAKgqQAGgaAJg0IAkjeIAjgGIAEgBIACAAIAQgDIACgBIADAAIAggGIABgCQACgCAFABIAFAAQBxgZBvgqQAcgLAKARQAGALgBAVQgDAngOAkQgNAjgWAbQgnAwg7ARIglAKQgUAIgNAPQgYAdgGBEQgGA4AFBwQAEBxgFA2IgGA7QgEAiACAYQACAWAFAaIANAuIAiBwQADgBADAAQAFAEgGAIgAgNUPQADABABADQABAGAAAMIADAOQAFAYgGANIgEAIQAEAEgDAJIgHAOQgEAMAPAVQAPAVAJAHQAQANAiAGQAjAGAVgEQARgEAWgMIAlgVIASgJQAKgGAFgIIAKgNIgahUQgTg9gEgkQgEgeADg3QAHhuAAg4IgEiIQgChRAKg1QAJgvATgXQANgRAYgIQAOgFAcgHQAogMAhgfQAjgiASgxQANglgCgfQgBgRgHgGQgGgGgOAFQg9AZg9ASIAjABIAKAAIAHABIAJAHIAQAMQADADABAFQABAGgDADQAJAHAGAKQACADgBACQAAACgDADQgBAGgCACQgCABgFgCQgQgHgPgBIgMgBQgLgBgVgLQgHgEgEgEQgDgDgBgDQgQgCgVABQgjACgiAHIAGABQAFABADACQgCAEgGABIgNABQgLAAgLgDIgTAFQgTAFgHgIQAEgHAGgFIgjAFQADAfgJAqQgEAXgMAwQgJAogLBUQgJA2gQAiQAJgEAFgFQAFgFAFgLIAXgwQAEgJABgFIAAAAQgBgKABgFIAEgJQABgDAAgEIgBgHIABgLIgBgKIgEgJQAAgIgBgEIgGgIQgEgFABgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQALANAFAQIACALQABAJAAASQAAAMgCAFIgCAHIgBAHIAWAIQARAFAHAGQAKAHADANQADANgEAMQgHAWgZAOQgLAGgHABQgGABgJgBIgiAAQgNAAgHgDIgEABIgGACIgDAEIgBgCQgMAEgLAAQgHgBgFgDQgOAHgZgGQgdgGgPgLQgXgQgDgWQgDgWAQgUQAKgOAYgPQAIgFAEgBIABAAIAAgKIABgOIACgIQACgGAAgMIAAgxIABgHQACgFAEACQADAIAAATIAAAkIgBASIgDAKIgBATIAAAkIABAUIACALQAEAMAFAHQAGALATASQAFAFADABIAJABQAIAAAIgDQhBiwgdjIIgJABIgDAAQgVAAg2gGQgkgDgZABQAEAEgFAGIgKAFQgLAEgKAJQgKAJgGAAQgDAAgFgCIgJgDIgIAAQgEAAgBgEIABgFQgMABgKgGIAUgQIANgJQAGgGAJgDIAHgCIAMgEIATgJQAIgCAPABIAEABIgvgWQiShKgfgLQgtgPgWAVQAwBTBSBGQAmAgBzBOQAQALAHAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gMDMQgGBigJA2QgOBTgkBfQgMAhgWAyQADABAFAFQAsAmBBADQA2ADAygVQApgTAJgdIgCgBQAAgFAFgLIAEgJQABgGAAgLIgBgsQAAgQAGgFQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAIABAAgAh8MDQgFALAAAJQACARARAOQAcAWAlgEIAEAAIgDgGQgFgBgHgJIgNgTIgHgRIgCgIIAAgzQgkAVgKAVgABHMGIgRAjQgIAQgHAHIgEADIANABQAUABALgBQARgCAMgGQARgKAEgRQAFgTgNgNQgGgHgTgGIgQgGQgCAJgHAPgAFBHcIACABIAFABIADABIADACQADABAFgCIgIgCIgIgCIgGgCIABACgAgXotQAKACANAMIANAOIACACQALAGAFAEIAMAQIAIAKIAKAJIAKAFQALAEAFAEQAIAGADgBIAEgCIAojnQAXiAALgvQAWhgAchCIAcg/QARglAHgbQAPg3gBhYQAAhDgKglQgLgngWgRQgFgEgHgDQgQgIgagFQj1gzj6AKIADA2QALDvAVEEIAKBhQAKBLAaBvIAsC4IADAQIAOgRQAHgHAGgFIAOgGQAKgEASgKQANgGAXgCIAUgJQAJgDAHAAIAIABgAh8oEQgTAKgJAJIAwgcQgJADgLAGg");
	this.shape_11.setTransform(447.9312,248.6845);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("ACsAhQgNgOAAgTQAAgSANgOIAOgBQAFgBACgEQgCgCgFgBQAFgCAFgCIAJgBQARABAMAJIAEAEIAHAJQAHALAAAMQAAATgOAOQgNAOgUAAQgTAAgOgOgAjtAhQgOgOAAgTQAAgSAOgOIAHgGQAIgFAJgCIAJgBIADAAQAPACALAIIAEAEIAHAJQAGALAAAMQAAAGgBAHQgDALgJAJQgOAOgTAAQgUAAgNgOg");
	this.shape_12.setTransform(448.475,299.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.rf(["#FF0000","#000000"],[0,1],28,-32,0,28,-32,94.3).s().p("ABbIOQgFgDgLgFIgKgFIgKgIIgIgLIgMgPQgFgFgLgGIgCgBIgOgPQgMgLgKgDQgLgCgNAEIgUAKQgXABgNAGIgcAOIgOAHQgGAEgHAIIgOAQIgDgPIgsi5QgahvgKhKIgKhhQgVkEgLjvIgDg2QD6gKD1A0QAaAEAQAIQAHADAFAEQAWARALAnQAKAlAABDQABBYgPA3QgHAbgRAmIgcA/QgcBBgWBfQgLAvgXCAIgoDoIgEACIAAAAQgEAAgHgGg");
	this.shape_13.setTransform(447.0031,148.0456);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AEzYDQgOgBgIgJQgIgJgHgYIgWhGQgHAIgKAIQgLAJgbAQQguAbgcADQgTADgigHQglgGgSgOQgQgNgUglQgTAWgaAOQgJAFgfALIgVAGQgFABgTAAQggAAgQgCQg7gIgtgmIggBHQgFALgFABQgFABgHgKQhyibhDhwIgVgkQhOiIgviFQgKgcAAgSQAAgQAKgdIBIjOQAHgUACgLQAEgSAAgPQgBgZgPgcIgcgtQgkg7gIhaQgIhNAMhaQARiCAxhpQAag5AggrQAfgqAlgcQAQgNAjgVQAigVARgNQAQgOAcgbQAfggAMgKQAcgYAwgfIAygeIg1jjQgXhlgGgnQgJg7gGhkIgjn4QgBgSAGgFQAFgFAPAAQCdADBOAFQCCAJBmAWQAuALAVAPIACACQAiAaAOA4QAaBoguCTQgLAighBWQgdBMgNAtQgRA+gZCpQgRB3gXBMQAEAAABAFQAAADgCAFQgEAEgEACQAXAOAaAOQAwAYBhAsQAxAZAdAeQARATAgAuIBVCAIAaAmQAZAnAOAZQAhA7AQA5QAXBQgDBgQgEBXgYBYQgHAYAEALQADAJAOAJQAiAVASArQAQAkABA1QACBLgeBkQgRA5gkBxQgGAYgOBIQgMA9gKAiQgPAygZAwQgPAcgRAbQgmA6g8BAQgbAegTAOQgaARgWAAIgFAAgAEAWIIgCACIAUBDQAGAWAHAIQAHAIAMACQAUAEAYgOQAQgKAXgXQBFhFAshGQATgdAPgfQAcg5APg9QAHgZAIguIANhGIA2itQAghoAAhKQgBg0gPgkQgRgogogdQgPgLgCgJQgDgLAHgXQAghlgDhwQgEh0gohbQgQglgdgrIgLgRIgog7QgthHgYgiQgog7glggQgjgeg6gZQhBgbgggQQgfgPgegUIgCAFIABgGIghgZIgCgBQgKgEgEgEQgFgDgFgIIgCgEIgYgWIgEgDQgPgKgGgHIgqAAIgIABQhGAkgpAYQgBAGgDAEIgBgGIgEACQhDAogyAsQg+A7ghAaQgQAMgqAbQglAYgUARQgdAZgZAjQgfAqgZA4QgpBdgSB0QgOBaAGBOQAIBbAiA7QAKARAVAhQARAeABAcQAAARgFAUQgDANgHAWIhJDQQgIAXAAANQgBASAMAgQA1CFBAB1QBTCYBnCAIAcAjIAkhMIABgDQAWgwANggQAjhbAPhRQAHgpAFg1IAGhgIAOkPQACgagBgOQgBgXgHgPQgGgOgMgLQgHgHgPgLQhfg/gvgoQhNhAgxhJQgLgQAAgNQABgNAMgGQAJgFAMACQA+AJCKBIQAzAaAqAQIAPAAQAqgBAgAKQALADAFAGQADAEABAFQAAADgBADQAfDHBAC0IAAgBQANgdAKgqQAGgaAJg0IAkjeIAjgGIAEgBIACAAIAQgDIACgBIADAAIAggGIABgCQACgCAFABIAFAAQBxgZBvgqQAcgLAKARQAGALgBAVQgDAngOAkQgNAjgWAbQgnAwg7ARIglAKQgUAIgNAPQgYAdgGBEQgGA4AFBwQAEBxgFA2IgGA7QgEAiACAYQACAWAFAaIANAuIAiBwQADgBADAAQAFAEgGAIgAgNUPQADABABADQABAGAAAMIADAOQAFAYgGANIgEAIQAEAEgDAJIgHAOQgEAMAPAVQAPAVAJAHQAQANAiAGQAjAGAVgEQARgEAWgMIAlgVIASgJQAKgGAFgIIAKgNIgahUQgTg9gEgkQgEgeADg3QAHhuAAg4IgEiIQgChRAKg1QAJgvATgXQANgRAYgIQAOgFAcgHQAogMAhgfQAjgiASgxQANglgCgfQgBgRgHgGQgGgGgOAFQg9AZg9ASIAjABIAKAAIAHABIAJAHIAQAMQADADABAFQABAGgDADQAJAHAGAKQACADgBACQAAACgDADQgBAGgCACQgCABgFgCQgQgHgPgBIgMgBQgLgBgVgLQgHgEgEgEQgDgDgBgDQgQgCgVABQgjACgiAHIAGABQAFABADACQgCAEgGABIgNABQgLAAgLgDIgTAFQgTAFgHgIQAEgHAGgFIgjAFQADAfgJAqQgEAXgMAwQgJAogLBUQgJA2gQAiQAJgEAFgFQAFgFAFgLIAXgwQAEgJABgFIAAAAQgBgKABgFIAEgJQABgDAAgEIgBgHIABgLIgBgKIgEgJQAAgIgBgEIgGgIQgEgFABgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQALANAFAQIACALQABAJAAASQAAAMgCAFIgCAHIgBAHIAWAIQARAFAHAGQAKAHADANQADANgEAMQgHAWgZAOQgLAGgHABQgGABgJgBIgiAAQgNAAgHgDIgEABIgGACIgDAEIgBgCQgMAEgLAAQgHgBgFgDQgOAHgZgGQgdgGgPgLQgXgQgDgWQgDgWAQgUQAKgOAYgPQAIgFAEgBIABAAIAAgKIABgOIACgIQACgGAAgMIAAgxIABgHQACgFAEACQADAIAAATIAAAkIgBASIgDAKIgBATIAAAkIABAUIACALQAEAMAFAHQAGALATASQAFAFADABIAJABQAIAAAIgDQhBiwgdjIIgJABIgDAAQgVAAg2gGQgkgDgZABQAEAEgFAGIgKAFQgLAEgKAJQgKAJgGAAQgDAAgFgCIgJgDIgIAAQgEAAgBgEIABgFQgMABgKgGIAUgQIANgJQAGgGAJgDIAHgCIAMgEIATgJQAIgCAPABIAEABIgvgWQiShKgfgLQgtgPgWAVQAwBTBSBGQAmAgBzBOQAQALAHAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gMDMQgGBigJA2QgOBTgkBfQgMAhgWAyQADABAFAFQAsAmBBADQA2ADAygVQApgTAJgdIgCgBQAAgFAFgLIAEgJQABgGAAgLIgBgsQAAgQAGgFQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAIABAAgAh8MDQgFALAAAJQACARARAOQAcAWAlgEIAEAAIgDgGQgFgBgHgJIgNgTIgHgRIgCgIIAAgzQgkAVgKAVgABHMGIgRAjQgIAQgHAHIgEADIANABQAUABALgBQARgCAMgGQARgKAEgRQAFgTgNgNQgGgHgTgGIgQgGQgCAJgHAPgAFBHcIACABIAFABIADABIADACQADABAFgCIgIgCIgIgCIgGgCIABACgAgXotQAKACANAMIANAOIACACQALAGAFAEIAMAQIAIAKIAKAJIAKAFQALAEAFAEQAIAGADgBIAEgCIAojnQAXiAALgvQAWhgAchCIAcg/QARglAHgbQAPg3gBhYQAAhDgKglQgLgngWgRQgFgEgHgDQgQgIgagFQj1gzj6AKIADA2QALDvAVEEIAKBhQAKBLAaBvIAsC4IADAQIAOgRQAHgHAGgFIAOgGIAcgOQANgGAXgCIAUgJQAJgDAHAAIAIABgAh8oEQgTAKgJAJIAwgcQgJADgLAGg");
	this.shape_14.setTransform(447.4312,247.6845);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#FFFFFF","#000000"],[0,1],49.1,-29.8,-124.8,107.7).s().p("AEyQGQgMgCgHgIQgHgIgGgWIgUhDIACgCQAGgIgFgEQgDAAgEABIghhwIgNguQgFgagCgWQgCgYAEgiIAGg7QAFg2gEhxQgFhwAGg4QAGhEAYgdQANgPAUgIIAlgKQA7gRAngwQAWgbANgiQAOgkADgnQABgVgGgLQgKgRgcALQhvAqhyAZIgEAAQgFgBgCACIgCACIggAGIgCAAIgDABIgPADIgCAAIgEABIgjAGIgkDdQgJA0gGAaQgKAqgNAdIgBABQhAi0gfjGQACgCAAgEQgBgFgDgEQgFgGgLgDQgggKgqABIgPAAQgrgQgygaQiKhIg+gJQgMgCgJAFQgMAGgBANQAAANALAQQAxBJBNBAQAvAnBfA/QAPALAHAHQAMALAGAOQAHAPABAXQABAOgCAaIgOEPIgGBgQgFA1gHApQgPBRgjBbQgNAggWAwIgBADIgkBMIgcgjQi2jih5kwQgMggABgSQAAgNAIgXIBJjQQAHgWADgNQAFgUAAgRQgBgcgRgeQgVgggKgRQgig7gIhbQgGhOAOhaQASh0ApheQAthmBBg4QAUgRAlgYQAqgbAQgMQAhgaA+g7QAygsBDgoIAEgCIABAGQADgEABgGQApgYBGgkIAIgBIAqAAQAGAHAPAKIAEADIAXAWIADAEQAFAIAFADQAEAEAKAEIABABQARANARAMIgBAGIACgFQAdAUAgAPQAgAQBBAbQA6AZAjAeQAlAgAoA7QAYAiAtBHIAzBMQAdAsAQAlQAoBbAEB0QADBwggBlQgHAXADAKQACAJAPALQAoAdARAoQAPAkABA0QAABKggBoIg2CtIgNBGQgIAugHAZQgXBdg2BVQgsBGhFBFQgXAXgQAKQgTALgQAAIgJgBg");
	this.shape_15.setTransform(448.4494,299.1694);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.rf(["#FF0000","#000000"],[0,1],28,-32,0,28,-32,94.3).s().p("ABbIOQgFgDgLgFIgKgFIgKgJIgIgKIgMgPQgFgFgLgGIgCgBIgOgPQgMgLgKgDQgLgCgNAEQgHACgNAIQgXABgNAGIgcAOIgOAHQgGAEgHAIIgOAQIgDgPIgsi5QgahvgKhKIgKhhQgXkhgMkIQD6gKD1A0QAkAGASANQAWARALAnQAKAlAABDQABBYgPA3QgHAbgRAmIgcA/QgcBBgWBfQgLAvgXCAIgoDoIgEACIAAAAQgEAAgHgGg");
	this.shape_16.setTransform(448.0031,150.0456);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AEzYDQgOgBgIgJQgIgJgHgYIgWhGQgHAIgKAIQgLAJgbAQQguAbgcADQgTADgigHQglgGgSgOQgQgNgUglQgTAWgaAOQgJAFgfALIgVAGQgFABgTAAQggAAgQgCQg7gIgtgmIggBHQgFALgFABQgFABgHgKQhyibhDhwQhdibg1iWQgKgcAAgSQAAgQAKgdIBIjOQAHgUACgLQAEgSAAgPQgBgZgPgcIgcgtQgkg7gIhaQgIhNAMhaQARiCAxhpQAzhxBLg5QAQgNAjgVQAigVARgNQAQgOAcgbQAfggAMgKQAcgYAwgfIAxgeIg0jjQgXhlgGgnQgJg7gGhkIgjn4QgBgSAGgFQAFgFAPAAQCdADBOAFQCCAJBmAWQAuALAVAPQAjAbAPA5QAaBoguCTQgLAighBWQgdBMgNAtQgRA+gZCpQgRB3gYBMQAFAAABAFQAAADgCAFQgEAEgEACQAXAOAaAOQAwAYBhAsQAxAZAdAeQARATAgAuIBVCAQAtBCAUAkQAhA7AQA5QAXBQgDBgQgEBXgYBYQgHAYAEALQADAJAOAJQAiAVASArQAQAkABA1QACBLgeBkQgRA5gkBxQgGAYgOBIQgMA9gKAiQgYBPgwBKQgmA6g8BAQgbAegTAOQgaARgWAAIgFAAgAEBV8QAFAEgGAIIgCACIAUBDQAGAWAHAIQAHAIAMACQAUAEAYgOQAQgKAXgXQBFhFAshGQA2hVAXhdQAHgZAIguIANhGIA2itQAghoAAhKQgBg0gPgkQgRgogogdQgPgLgCgJQgDgLAHgXQAghlgDhwQgEh0gohbQgQglgdgrIgzhMQgthHgYgiQgog7glggQgjgeg6gZQhBgbgggQQgfgPgegVIgCAGIABgGQgRgMgRgNIgBgBQgKgEgEgEQgFgDgFgIIgDgEIgXgWIgEgDQgPgKgGgHIgqAAIgIABQhGAkgpAYQgBAGgDAEIgBgHIgEADQhDAogyAsQg+A7ghAaQgQAMgqAbQglAYgUARQhBA4gtBmQgpBdgSB0QgOBaAGBOQAIBbAiA7QAKARAVAhQARAeABAcQAAARgFAUQgDANgHAWIhJDQQgIAXAAANQgBASAMAgQB5EwC2DiIAcAjIAkhMIABgDQAWgwANggQAjhbAPhRQAHgpAFg1IAGhgIAOkPQACgagBgOQgBgXgHgPQgGgOgMgLQgHgHgPgLQhfg/gvgoQhNhAgxhJQgLgQAAgNQABgNAMgGQAJgFAMACQA+AJCKBIQAyAaArAQIAPAAQAqgBAgAKQALADAFAGQADAEABAFQAAADgCADQAgDHA/CzIABAAQANgdAKgqQAGgaAJg0IAkjeIAjgGIAEgBIACAAIAPgDIADgBIACAAIAggGIACgCQACgCAFABIAEAAQBygZBvgqQAcgLAKARQAGALgBAVQgDAngOAkQgNAjgWAbQgnAwg7ARIglAKQgUAIgNAPQgYAdgGBEQgGA4AFBwQAEBxgFA2IgGA7QgEAiACAYQACAWAFAaIANAuIAhBwQADgBADAAIABAAgAgNUPQADABABADQABAGAAAMIADAOQAFAYgGANIgEAHQAEAFgDAJIgHAOQgEAMAPAVQAPAVAJAHQAQANAiAGQAjAGAVgEQARgEAWgMIAlgVIASgJQAKgGAFgIIAKgNIgahUQgTg9gEgkQgEgeADg3QAHhuAAg4IgEiIQgChRAKg1QAJgvATgXQANgRAYgIQAOgFAcgHQAogMAhgfQAjgiASgxQANglgCgfQgBgRgHgGQgGgGgOAFQg9AZg9ASIAjABIAKAAIAHABIAJAHIAQAMQADADABAFQABAGgDADQAJAHAGAKQACADgBACQAAACgDADQgBAGgCACQgCABgFgCQgQgHgPgBIgMgBQgLgBgVgLQgHgEgEgEQgDgDgBgDQgQgCgVABQgjACgiAHIAGAAQAFACADACQgCAEgGABIgNABQgLAAgLgEIgTAGQgTAFgHgIQAEgHAGgFIgjAFQADAfgJAqQgEAXgMAwQgJAogLBUQgJA2gQAiQAJgEAFgFQAFgFAFgLIAXgwQAEgJABgFIAAAAQgBgKABgFIAEgJQABgDAAgEIgBgHIABgLIgBgKIgEgJQAAgIgBgEIgGgIQgEgFABgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQALANAFAQIACALQABAJAAASQAAAMgCAFIgCAHIgBAHQAHADAPAFQARAFAHAGQAKAHADANQADANgEAMQgHAWgZAOQgLAGgHABQgGABgJgBIgiAAQgNAAgIgEIgDACIgGACIgDAEIgBgDQgMAFgLAAQgHgBgGgDQgNAHgZgGQgdgGgPgLQgXgQgDgWQgDgWAQgUQAKgOAYgPQAIgFAEgBIABAAIAAgKIABgOIACgIQACgGAAgMIAAgxIABgHQACgFAEACQADAIAAATIAAAkIgBASIgDAKIgBATIAAAkIABAUIACALQAEAMAFAHQAGALATASQAFAFADABIAJABQAIAAAIgDQhBiwgdjJIgJACIgDAAQgVAAg2gGQgkgDgaABQAFAEgFAGIgKAFQgLAEgKAJQgKAJgGAAQgDAAgFgCIgJgDIgIAAQgEAAgBgEIABgFQgMABgKgGIAUgQIANgKQAGgFAJgDIAHgCIAMgEIATgJQAIgCAPABIAEAAQgXgJgYgMQiShKgfgLQgtgPgWAVQAwBTBSBGQAmAgBzBOQAQALAHAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gMDMQgGBigJA2QgOBTgkBfQgMAhgXAyQAEABAFAFQAsAmBBADQA2ADAygVQApgTAJgdIgCgBQAAgFAFgLIAEgJQABgGAAgLIgBgsQAAgQAGgFQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAIABAAgAh8MDQgFALAAAJQACARARAOQAcAWAlgEIAEAAIgDgGQgFgBgHgJIgNgTIgHgRIgCgIIAAgzQgkAUgKAWgABHMGIgRAjQgIAQgHAHIgEADIANABQAUABALgBQARgCAMgGQARgKAEgRQAFgTgNgNQgGgHgTgGQgKgDgGgDQgCAJgHAPgAFBHcIACABIAFABIADABIADACQADABAFgCIgIgCIgIgCIgGgCIABACgAgXotQAKACANAMIANAOIACACQALAGAFAEIAMAQIAIAKIAKAIIAKAGQALAEAFAEQAIAGADgBIAEgCIAojnQAXiAALgvQAWhgAchCIAcg/QARglAHgbQAPg3gBhYQAAhDgKglQgLgngWgRQgSgNgkgHQj1gzj6AKQAMEHAXEiIAKBhQAKBLAaBvIAsC4IACAQIAPgRQAHgHAGgFIAOgGIAcgOQANgGAWgCQAOgHAHgCQAJgDAHAAIAIABgAh8oEQgTAKgKAJIAxgdIgUAKg");
	this.shape_17.setTransform(448.4312,249.6845);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#000000").ss(1,1,1).p("ADFgeQAEgBAEAAQARAAAMAHQACABACABQAEADADAEQAGAHABAIIAAABQgBANgNAJQgNAJgUAAQgTAAgOgJQgNgJAAgNIAAgBQAAgLAKgIAieAAIAAABQAAAEgBAEQgDAIgJAHQgOAJgTAAQgUAAgNgJQgNgJgBgNIAAgCQABgNANgKQADgCAEgCQAIgDAJgBQAEgBAFAAQACAAABAAQAPABALAGQACACACAAQAEADADAEQAGAHAAAJg");
	this.shape_18.setTransform(448.975,301.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AjtAXQgNgIgBgNIAAgCQABgNANgKIAHgDQAIgEAJgBIAJgBIADAAQAPABALAGIAEACIAHAHQAGAHAAAJIAAABIgBAIQgDAIgJAGQgOAKgTAAQgUAAgNgKgACsAXQgNgJAAgNIAAgBQAAgLAKgIIAAABQABAAAAAAQAAAAABABQAAAAABAAQABAAABAAQAGAAADgBIAHgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBAAAAQAEgBAAgDIAAgCIABAAIAAgCIAIAAQARAAAMAHIAEACIAHAHQAGAHABAIIAAABQgBANgNAJQgNAJgUAAQgTAAgOgJg");
	this.shape_19.setTransform(448.975,301.25);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFCC99").s().p("ABnJIQgigGgQgNQgJgHgQgVQgPgVAEgMIAHgOQADgJgEgEIAEgIQAGgNgFgYIgDgOQAAgMgBgGQgBgDgDgBQgDgBgCADQgGAFAAAQIABAsQAAALgBAGIgEAJQgFALAAAFIACABQgHAdgqATQgyAVg2gDQhBgDgsgmQgFgFgDgBQAWgyAMghQAkhfAOhTQAJg2AGhiQAMjLACh7IAAgbQgBgPgEgKQgFgPgMgMQgHgIgQgLQhzhOgmggQhShGgwhTQAWgVAtAPQAfALCSBKQAYAMAXAKIgEgBQgPgBgIACIgTAJIgMAEIgHACQgJADgGAGIgNAJIgUAQQAKAGAMgBIgBAFQABAEAEAAIAIAAIAJADQAFACADAAQAGAAAKgJQAKgJALgEIAKgFQAFgFgEgFQAZgBAkADQA2AGAVAAIADAAIAJgBQAdDIBBCwQgJADgIAAIgJgBQgDgBgFgFQgSgSgGgLQgFgHgEgMIgCgLIgBgUIAAgkIABgTIADgKIABgSIAAgkQAAgTgDgIQgEgCgCAFIgBAHIAAAxQAAAMgCAGIgCAIIgBAOIAAAKIgBAAQgEABgIAFQgYAPgKAOQgQAUADAWQADAWAXAQQAPALAdAGQAZAGANgHQAGADAGABQALAAANgEIABACIADgEIAGgCIAEgBQAIADAMAAIAiAAQAJABAGgBQAHgBALgGQAZgOAHgWQAEgMgDgNQgDgNgKgHQgHgGgRgFQgPgEgHgEIABgHIACgHQACgFAAgMQAAgSgBgJIgCgLQgFgQgLgNQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBAEAEAFIAGAIQABAEAAAIIAEAJIABAKIgBALIABAHQAAAEgBADIgEAJQgBAFABAKIAAAAQgBAFgEAJIgXAwQgFALgFAFQgFAFgJAEQAQghAJg3QALhUAJgoQAMgwAEgXQAJgqgDgfIAjgFQgGAFgEAHQAHAIATgFIATgFQALADALAAIAHAAQgEABgDACQgDABgCADQgBAEACACQgJAIgBALIAAACQABANANAJQANAJAUAAQATAAAOgJQANgJAAgNIAAgCQAAgJgGgHIgHgGIgEgCQgNgHgQAAIgIAAIAAAAIgBgCIgBgCIgDgBIAAABIgCAAIADgDQgCgCgGgBIgGgBQAigHAjgCQAWgBAPACQABADADADQAEAEAHAEQAVALALABIAMABQAPABAQAHQAFACACgBQACgCABgGQADgDAAgCQABgCgCgDQgGgKgJgHQADgDgBgGQgBgFgDgDIgQgMIgJgHIgHgBIgKAAIgjgBQA9gSA9gZQAOgFAGAGQAHAGABARQACAfgNAlQgSAxgjAiQghAfgoAMQgcAHgOAFQgYAIgNARQgTAXgJAvQgKA1ACBRIAECHQAAA4gHBuQgDA3AEAeQAEAkATA9IAaBUIgKANQgFAIgKAGIgSAJIglAVQgWAMgRAEQgIACgLAAQgQAAgVgEgAiumeQgJABgHADIgIAEQgMAKgBANIAAADQABANAMAIQAOAKATAAQAUAAANgKQAJgGADgIIACgIIAAgCQgBgJgGgHIgHgHIgEgCQgLgGgOgBIgEAAIgJABgAhMhMQgRgOgCgRQAAgJAFgLQAKgVAkgVIAAAzIACAIIAHARIANATQAHAJAFABIADAGIgEAAIgLABQgeAAgYgTgABSg+IgNgBIAEgDQAHgHAIgQIARgjQAHgPACgJQAHAEAJACQATAGAGAHQANANgFATQgEARgRAKQgMAGgRACIgNAAIgSAAgADhmgIAEgBIgBABgAFwmhIgDgCIgDgBIgFgBIgCgBIgBgCIAGACIAIACIAIACIgFABIgDAAg");
	this.shape_20.setTransform(445.0133,339.5545);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AEzYDQgOgBgIgJQgIgJgHgYIgWhGQgHAIgKAIQgLAJgbAQQguAbgcADQgTADgigHQglgGgSgOQgQgNgUglQgTAWgaAOQgJAFgfALIgVAGQgFABgTAAQggAAgQgCQg7gIgtgmIggBHQgFALgFABQgFABgHgKQhyibhDhwQhdibg1iWQgKgcAAgSQAAgQAKgdIBIjOQAHgUACgLQAEgSAAgPQgBgZgPgcIgcgtQgkg7gIhaQgIhNAMhaQARiCAxhpQAzhxBLg5QAQgNAjgVQAigVARgNQAQgOAcgbQAfggAMgKQAcgYAwgfIAxgeIg0jjQgXhlgGgnQgJg7gGhkIgjn4QgBgSAGgFQAFgFAPAAQCdADBOAFQCCAJBmAWQAuALAVAPQAjAbAPA5QAaBoguCTQgLAighBWQgdBMgNAtQgRA+gZCpQgRB3gYBMQAFAAABAFQAAADgCAFQgEAEgEACQAXAOAaAOQAwAYBhAsQAxAZAdAeQARATAgAuIBVCAQAtBCAUAkQAhA7AQA5QAXBQgDBgQgEBXgYBYQgHAYAEALQADAJAOAJQAiAVASArQAQAkABA1QACBLgeBkQgRA5gkBxQgGAYgOBIQgMA9gKAiQgYBPgwBKQgmA6g8BAQgbAegTAOQgaARgWAAIgFAAgAEBV8QAFAEgGAIIgCACIAUBDQAGAWAHAIQAHAIAMACQAUAEAYgOQAQgKAXgXQBFhFAshGQA2hVAXhdQAHgZAIguIANhGIA2itQAghoAAhKQgBg0gPgkQgRgogogdQgPgLgCgJQgDgLAHgXQAghlgDhwQgEh0gohbQgQglgdgrIgzhMQgthHgYgiQgog7glggQgjgeg6gZQhBgbgggQQgfgPgegVIgCAGIABgGQgRgMgRgNIgBgBQgKgEgEgEQgFgDgFgIIgDgEIgXgWIgEgDQgPgKgGgHIgqAAIgIABQhGAkgpAYQgBAGgDAEIgBgHIgEADQhDAogyAsQg+A7ghAaQgQAMgqAbQglAYgUARQhBA4gtBmQgpBdgSB0QgOBaAGBOQAIBbAiA7QAKARAVAhQARAeABAcQAAARgFAUQgDANgHAWIhJDQQgIAXAAANQgBASAMAgQB5EwC2DiIAcAjIAkhMIABgDQAWgwANggQAjhbAPhRQAHgpAFg1IAGhgIAOkPQACgagBgOQgBgXgHgPQgGgOgMgLQgHgHgPgLQhfg/gvgoQhNhAgxhJQgLgQAAgNQABgNAMgGQAJgFAMACQA+AJCKBIQAyAaArAQIAPAAQAqgBAgAKQALADAFAGQADAEABAFQAAADgCADQAgDHA/CzIABAAQANgdAKgqQAGgaAJg0IAkjeIAjgGIAEgBIACAAIAPgDIADgBIACAAIAggGIACgCQACgCAFABIAEAAQBygZBvgqQAcgLAKARQAGALgBAVQgDAngOAkQgNAjgWAbQgnAwg7ARIglAKQgUAIgNAPQgYAdgGBEQgGA4AFBwQAEBxgFA2IgGA7QgEAiACAYQACAWAFAaIANAuIAhBwQADgBADAAIABAAgAgNUPQADABABADQABAGAAAMIADAOQAFAYgGANIgEAHQAEAFgDAJIgHAOQgEAMAPAVQAPAVAJAHQAQANAiAGQAjAGAVgEQARgEAWgMIAlgVIASgJQAKgGAFgIIAKgNIgahUQgTg9gEgkQgEgeADg3QAHhuAAg4IgEiIQgChRAKg1QAJgvATgXQANgRAYgIQAOgFAcgHQAogMAhgfQAjgiASgxQANglgCgfQgBgRgHgGQgGgGgOAFQg9AZg9ASIAjABIAKAAIAHABIAJAHIAQAMQADADABAFQABAGgDADQAJAHAGAKQACADgBACQAAACgDADQgBAGgCACQgCABgFgCQgQgHgPgBIgMgBQgLgBgVgLQgHgEgEgEQgDgDgBgDQgQgCgVABQgjACgiAHIAGAAQAFACADACIgDADIACAAIAAgBIADABIABACIABACIAAAAIgBACIAAAAIAAABQgBADgDACQgBAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAABIgGACQgDACgHAAQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAAAAAgBIgBAAQgDgCACgEQACgDADgBQADgDAEgBIgHABQgLAAgLgEIgTAGQgTAFgHgIQAEgHAGgFIgjAFQADAfgJAqQgEAXgMAwQgJAogLBUQgJA2gQAiQAJgEAFgFQAFgFAFgLIAXgwQAEgJABgFIAAAAQgBgKABgFIAEgJQABgDAAgEIgBgHIABgLIgBgKIgEgJQAAgIgBgEIgGgIQgEgFABgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQALANAFAQIACALQABAJAAASQAAAMgCAFIgCAHIgBAHQAHADAPAFQARAFAHAGQAKAHADANQADANgEAMQgHAWgZAOQgLAGgHABQgGABgJgBIgiAAQgNAAgIgEIgDACIgGACIgDAEIgBgDQgMAFgLAAQgHgBgGgDQgNAHgZgGQgdgGgPgLQgXgQgDgWQgDgWAQgUQAKgOAYgPQAIgFAEgBIABAAIAAgKIABgOIACgIQACgGAAgMIAAgxIABgHQACgFAEACQADAIAAATIAAAkIgBASIgDAKIgBATIAAAkIABAUIACALQAEAMAFAHQAGALATASQAFAFADABIAJABQAIAAAIgDQhBiwgdjJIgJACIgDAAQgVAAg2gGQgkgDgaABQAFAEgFAGIgKAFQgLAEgKAJQgKAJgGAAQgDAAgFgCIgJgDIgIAAQgEAAgBgEIABgFQgMABgKgGIAUgQIANgKQAGgFAJgDIAHgCIAMgEIATgJQAIgCAPABIAEAAQgXgJgYgMQiShKgfgLQgtgPgWAVQAwBTBSBGQAmAgBzBOQAQALAHAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gMDMQgGBigJA2QgOBTgkBfQgMAhgXAyQAEABAFAFQAsAmBBADQA2ADAygVQApgTAJgdIgCgBQAAgFAFgLIAEgJQABgGAAgLIgBgsQAAgQAGgFQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAIABAAgAh8MDQgFALAAAJQACARARAOQAcAWAlgEIAEAAIgDgGQgFgBgHgJIgNgTIgHgRIgCgIIAAgzQgkAUgKAWgABHMGIgRAjQgIAQgHAHIgEADIANABQAUABALgBQARgCAMgGQARgKAEgRQAFgTgNgNQgGgHgTgGQgKgDgGgDQgCAJgHAPgAC/HiIADAAIABgBIgEABgAFBHcIACABIAFABIADABIADACQADABAFgCIgIgCIgIgCIgGgCIABACgAgXotQAKACANAMIANAOIACACQALAGAFAEIAMAQIAIAKIAKAIIAKAGQALAEAFAEQAIAGADgBIAEgCIAojnQAXiAALgvQAWhgAchCIAcg/QARglAHgbQAPg3gBhYQAAhDgKglQgLgngWgRQgSgNgkgHQj1gzj6AKQAMEHAXEiIAKBhQAKBLAaBvIAsC4IACAQIAPgRQAHgHAGgFIAOgGIAcgOQANgGAWgCQAOgHAHgCQAJgDAHAAIAIABgAh8oEQgTAKgKAJIAxgdIgUAKg");
	this.shape_21.setTransform(448.4312,249.6845);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#000000").ss(1,1,1).p("ADAgYQACAAACAAQAFgBAEAAQARAAAMAGQACABACABQAEACADADQAHAFAAAHIAAABQgBAKgNAHQgNAIgUAAQgTAAgOgIQgNgHAAgKIAAgBQAAgIAJgGAieAAIAAABQAAADgBADQgDAGgJAFQgOAIgTAAQgUAAgNgIQgNgHgBgKIAAgBQABgKANgHQADgCAEgCQAIgCAJgBQAEgBAFAAQACAAABAAQAPABALAFQACABACABQAEACADADQAGAFAAAHg");
	this.shape_22.setTransform(448.975,301.275);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("ACsASQgNgHAAgKIAAgBQAAgIAJgGIADABQACACADgCIAGgDIAGgBIADgCIACgBIgBgBIAAgBIAAgCIAEAAIAJgBQARAAAMAGIAEACIAHAFQAHAFAAAHIAAABQgBAKgNAHQgNAIgUAAQgTAAgOgIgAjtASQgNgHgBgKIAAgBQABgKANgHIAHgEQAIgCAJgBIAJgBIADAAQAPABALAFIAEACIAHAFQAGAFAAAHIAAABIgBAGQgDAGgJAFQgOAIgTAAQgUAAgNgIg");
	this.shape_23.setTransform(448.975,301.275);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFCC99").s().p("ABnJIQgigGgQgNQgJgHgQgVQgPgVAEgMIAHgOQADgJgEgEIAEgIQAGgNgFgYIgDgOQAAgMgBgGQgBgDgDgBQgDgBgCADQgGAFAAAQIABAsQAAALgBAGIgEAJQgFALAAAFIACABQgHAdgqATQgyAVg2gDQhBgDgsgmQgFgFgDgBQAWgyAMghQAkhfAOhTQAJg2AGhiQAMjLACh7IAAgbQgBgPgEgKQgFgPgMgMQgHgIgQgLQhzhOgmggQhShGgwhTQAWgVAtAPQAfALCSBKQAYAMAXAKIgEgBQgPgBgIACIgTAJIgMAEIgHACQgJADgGAGIgNAJIgUAQQAKAGAMgBIgBAFQABAEAEAAIAIAAIAJADQAFACADAAQAGAAAKgJQAKgJALgEIAKgFQAFgFgEgFQAZgBAkADQA2AGAVAAIADAAIAJgBQAdDIBBCwQgJADgIAAIgJgBQgDgBgFgFQgSgSgGgLQgFgHgEgMIgCgLIgBgUIAAgkIABgTIADgKIABgSIAAgkQAAgTgDgIQgEgCgCAFIgBAHIAAAxQAAAMgCAGIgCAIIgBAOIAAAKIgBAAQgEABgIAFQgYAPgKAOQgQAUADAWQADAWAXAQQAPALAdAGQAZAGANgHQAGADAGABQALAAANgEIABACIADgEIAGgCIAEgBQAIADAMAAIAiAAQAJABAGgBQAHgBALgGQAZgOAHgWQAEgMgDgNQgDgNgKgHQgHgGgRgFQgPgEgHgEIABgHIACgHQACgFAAgMQAAgSgBgJIgCgLQgFgQgLgNQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBAEAEAFIAGAIQABAEAAAIIAEAJIABAKIgBALIABAHQAAAEgBADIgEAJQgBAFABAKIAAAAQgBAFgEAJIgXAwQgFALgFAFQgFAFgJAEQAQghAJg3QALhUAJgoQAMgwAEgXQAJgqgDgfIAjgFQgGAFgEAHQAHAIATgFIATgFQALADALAAIANgBQAGgBACgEQgCgCgGgBIgGgBQAigHAjgCQAWgBAPACQABADADADQAEAEAHAEQAVALALABIAMABQAPABAQAHQAFACACgBQACgCABgGQADgDAAgCQABgCgCgDQgGgKgJgHQADgDgBgGQgBgFgDgDIgQgMIgJgHIgHgBIgKAAIgjgBQA9gSA9gZQAOgFAGAGQAHAGABARQACAfgNAlQgSAxgjAiQghAfgoAMQgcAHgOAFQgYAIgNARQgTAXgJAvQgKA1ACBRIAECHQAAA4gHBuQgDA3AEAeQAEAkATA9IAaBUIgKANQgFAIgKAGIgSAJIglAVQgWAMgRAEQgIACgLAAQgQAAgVgEgADdmaQgJADgFAEQgBAEACACQgJAGgBAIIAAACQABAKANAHQANAIAUAAQATAAAOgIQANgHAAgKIAAgCQAAgHgGgFIgHgFIgEgCQgNgGgQAAIgJABIgEAAQgBgCgEgBIgBAAIgFAAgAiumXQgJABgHACIgIAEQgNAHAAAKIAAACQAAAKANAHQAOAIATAAQAUAAANgIQAJgFADgGIACgGIAAgCQAAgHgHgFIgHgFIgEgCQgLgFgOgBIgEAAIgJABgAhMhMQgRgOgCgRQAAgJAFgLQAKgVAkgVIAAAzIACAIIAHARIANATQAHAJAFABIADAGIgEAAIgLABQgeAAgYgTgABSg+IgNgBIAEgDQAHgHAIgQIARgjQAHgPACgJQAHAEAJACQATAGAGAHQANANgFATQgEARgRAKQgMAGgRACIgNAAIgSAAgADomUIABABIgDABIACgCgAFwmhIgDgCIgDgBIgFgBIgCgBIgBgCIAGACIAIACIAIACIgFABIgDAAg");
	this.shape_24.setTransform(445.0133,339.5545);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AEzYDQgOgBgIgJQgIgJgHgYIgWhGQgHAIgKAIQgLAJgbAQQguAbgcADQgTADgigHQglgGgSgOQgQgNgUglQgTAWgaAOQgJAFgfALIgVAGQgFABgTAAQggAAgQgCQg7gIgtgmIggBHQgFALgFABQgFABgHgKQhyibhDhwQhdibg1iWQgKgcAAgSQAAgQAKgdIBIjOQAHgUACgLQAEgSAAgPQgBgZgPgcIgcgtQgkg7gIhaQgIhNAMhaQARiCAxhpQAzhxBLg5QAQgNAjgVQAigVARgNQAQgOAcgbQAfggAMgKQAcgYAwgfIAxgeIg0jjQgXhlgGgnQgJg7gGhkIgjn4QgBgSAGgFQAFgFAPAAQCdADBOAFQCCAJBmAWQAuALAVAPQAjAbAPA5QAaBoguCTQgLAighBWQgdBMgNAtQgRA+gZCpQgRB3gYBMQAFAAABAFQAAADgCAFQgEAEgEACQAXAOAaAOQAwAYBhAsQAxAZAdAeQARATAgAuIBVCAQAtBCAUAkQAhA7AQA5QAXBQgDBgQgEBXgYBYQgHAYAEALQADAJAOAJQAiAVASArQAQAkABA1QACBLgeBkQgRA5gkBxQgGAYgOBIQgMA9gKAiQgYBPgwBKQgmA6g8BAQgbAegTAOQgaARgWAAIgFAAgAEBV8QAFAEgGAIIgCACIAUBDQAGAWAHAIQAHAIAMACQAUAEAYgOQAQgKAXgXQBFhFAshGQA2hVAXhdQAHgZAIguIANhGIA2itQAghoAAhKQgBg0gPgkQgRgogogdQgPgLgCgJQgDgLAHgXQAghlgDhwQgEh0gohbQgQglgdgrIgzhMQgthHgYgiQgog7glggQgjgeg6gZQhBgbgggQQgfgPgegVIgCAGIABgGQgRgMgRgNIgBgBQgKgEgEgEQgFgDgFgIIgDgEIgXgWIgEgDQgPgKgGgHIgqAAIgIABQhGAkgpAYQgBAGgDAEIgBgHIgEADQhDAogyAsQg+A7ghAaQgQAMgqAbQglAYgUARQhBA4gtBmQgpBdgSB0QgOBaAGBOQAIBbAiA7QAKARAVAhQARAeABAcQAAARgFAUQgDANgHAWIhJDQQgIAXAAANQgBASAMAgQB5EwC2DiIAcAjIAkhMIABgDQAWgwANggQAjhbAPhRQAHgpAFg1IAGhgIAOkPQACgagBgOQgBgXgHgPQgGgOgMgLQgHgHgPgLQhfg/gvgoQhNhAgxhJQgLgQAAgNQABgNAMgGQAJgFAMACQA+AJCKBIQAyAaArAQIAPAAQAqgBAgAKQALADAFAGQADAEABAFQAAADgCADQAgDHA/CzIABAAQANgdAKgqQAGgaAJg0IAkjeIAjgGIAEgBIACAAIAPgDIADgBIACAAIAggGIACgCQACgCAFABIAEAAQBygZBvgqQAcgLAKARQAGALgBAVQgDAngOAkQgNAjgWAbQgnAwg7ARIglAKQgUAIgNAPQgYAdgGBEQgGA4AFBwQAEBxgFA2IgGA7QgEAiACAYQACAWAFAaIANAuIAhBwQADgBADAAIABAAgAgNUPQADABABADQABAGAAAMIADAOQAFAYgGANIgEAHQAEAFgDAJIgHAOQgEAMAPAVQAPAVAJAHQAQANAiAGQAjAGAVgEQARgEAWgMIAlgVIASgJQAKgGAFgIIAKgNIgahUQgTg9gEgkQgEgeADg3QAHhuAAg4IgEiIQgChRAKg1QAJgvATgXQANgRAYgIQAOgFAcgHQAogMAhgfQAjgiASgxQANglgCgfQgBgRgHgGQgGgGgOAFQg9AZg9ASIAjABIAKAAIAHABIAJAHIAQAMQADADABAFQABAGgDADQAJAHAGAKQACADgBACQAAACgDADQgBAGgCACQgCABgFgCQgQgHgPgBIgMgBQgLgBgVgLQgHgEgEgEQgDgDgBgDQgQgCgVABQgjACgiAHIAGAAQAFACADACQgCAEgGABIgNABQgLAAgLgEIgTAGQgTAFgHgIQAEgHAGgFIgjAFQADAfgJAqQgEAXgMAwQgJAogLBUQgJA2gQAiQAJgEAFgFQAFgFAFgLIAXgwQAEgJABgFIAAAAQgBgKABgFIAEgJQABgDAAgEIgBgHIABgLIgBgKIgEgJQAAgIgBgEIgGgIQgEgFABgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQALANAFAQIACALQABAJAAASQAAAMgCAFIgCAHIgBAHQAHADAPAFQARAFAHAGQAKAHADANQADANgEAMQgHAWgZAOQgLAGgHABQgGABgJgBIgiAAQgNAAgIgEIgDACIgGACIgDAEIgBgDQgMAFgLAAQgHgBgGgDQgNAHgZgGQgdgGgPgLQgXgQgDgWQgDgWAQgUQAKgOAYgPQAIgFAEgBIABAAIAAgKIABgOIACgIQACgGAAgMIAAgxIABgHQACgFAEACQADAIAAATIAAAkIgBASIgDAKIgBATIAAAkIABAUIACALQAEAMAFAHQAGALATASQAFAFADABIAJABQAIAAAIgDQhBiwgdjJIgJACIgDAAQgVAAg2gGQgkgDgaABQAFAEgFAGIgKAFQgLAEgKAJQgKAJgGAAQgDAAgFgCIgJgDIgIAAQgEAAgBgEIABgFQgMABgKgGIAUgQIANgKQAGgFAJgDIAHgCIAMgEIATgJQAIgCAPABIAEAAQgXgJgYgMQiShKgfgLQgtgPgWAVQAwBTBSBGQAmAgBzBOQAQALAHAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gMDMQgGBigJA2QgOBTgkBfQgMAhgXAyQAEABAFAFQAsAmBBADQA2ADAygVQApgTAJgdIgCgBQAAgFAFgLIAEgJQABgGAAgLIgBgsQAAgQAGgFQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAIABAAgAh8MDQgFALAAAJQACARARAOQAcAWAlgEIAEAAIgDgGQgFgBgHgJIgNgTIgHgRIgCgIIAAgzQgkAUgKAWgABHMGIgRAjQgIAQgHAHIgEADIANABQAUABALgBQARgCAMgGQARgKAEgRQAFgTgNgNQgGgHgTgGQgKgDgGgDQgCAJgHAPgAFBHcIACABIAFABIADABIADACQADABAFgCIgIgCIgIgCIgGgCIABACgAgXotQAKACANAMIANAOIACACQALAGAFAEIAMAQIAIAKIAKAIIAKAGQALAEAFAEQAIAGADgBIAEgCIAojnQAXiAALgvQAWhgAchCIAcg/QARglAHgbQAPg3gBhYQAAhDgKglQgLgngWgRQgSgNgkgHQj1gzj6AKQAMEHAXEiIAKBhQAKBLAaBvIAsC4IACAQIAPgRQAHgHAGgFIAOgGIAcgOQANgGAWgCQAOgHAHgCQAJgDAHAAIAIABgAh8oEQgTAKgKAJIAxgdIgUAKgACwH2IgDgCQgBgCABgDQAFgEAJgDIAGAAQAEAAAAADIABACIgBABIgBACIgCACIgHABIgFADIgEABIgCgBg");
	this.shape_25.setTransform(448.4312,249.6845);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#000000").ss(1,1,1).p("AC7gEQAFAAAEAAQAFAAAEAAQARAAAMABQACAAACAAQAEABADAAQAHACAAAAQAAACgOABQgNACgUAAQgNAAgKgBACzAEQgDAAgEgBQgNgBAAgCQAAgBANgCAirADQgOACgTAAQgUAAgNgCQgOgBAAgCQAAgBAOgCQADAAAEAAQAIgBAJAAQAEAAAFAAQACAAABAAQAPAAALABQACAAACAAQAEABADAAQAGACAAAAQAAABgBAAQgDACgJAAg");
	this.shape_26.setTransform(448.975,301.275);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AC2AEIADgBIAAgBIABAAIAAgBIAAgBIABAAIAAgBIAAgCIAGAAIgGgBIAJAAIAJAAIAdABIAEAAIAHABQAHACAAAAQAAACgOABQgNACgUAAIgXgBgAjtADQgOgBAAgCQAAgBAOgCIAHAAIARgBIAJAAIADAAIAaABIAEAAIAHABQAGACAAAAIgBABQgDACgJAAQgOACgTAAQgUAAgNgCgACsADQgNgBAAgCQAAgBANgCQAAABAAABQAAAAAAABQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAAABABAAQAAAAABAAIAAAAIAAAAIACADIgHgBg");
	this.shape_27.setTransform(448.975,301.275);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFCC99").s().p("ABnJIQgigGgQgNQgJgHgQgVQgPgVAEgMIAHgOQADgJgEgEIAEgIQAGgNgFgYIgDgOQAAgMgBgGQgBgDgDgBQgDgBgCADQgGAFAAAQIABAsQAAALgBAGIgEAJQgFALAAAFIACABQgHAdgqATQgyAVg2gDQhBgDgsgmQgFgFgDgBQAWgyAMghQAkhfAOhTQAJg2AGhiQAMjLACh7IAAgbQgBgPgEgKQgFgPgMgMQgHgIgQgLQhzhOgmggQhShGgwhTQAWgVAtAPQAfALCSBKQAYAMAXAKIgEgBQgPgBgIACIgTAJIgMAEIgHACQgJADgGAGIgNAJIgUAQQAKAGAMgBIgBAFQABAEAEAAIAIAAIAJADQAFACADAAQAGAAAKgJQAKgJALgEIAKgFQAFgFgEgFQAZgBAkADQA2AGAVAAIADAAIAJgBQAdDIBBCwQgJADgIAAIgJgBQgDgBgFgFQgSgSgGgLQgFgHgEgMIgCgLIgBgUIAAgkIABgTIADgKIABgSIAAgkQAAgTgDgIQgEgCgCAFIgBAHIAAAxQAAAMgCAGIgCAIIgBAOIAAAKIgBAAQgEABgIAFQgYAPgKAOQgQAUADAWQADAWAXAQQAPALAdAGQAZAGANgHQAGADAGABQALAAANgEIABACIADgEIAGgCIAEgBQAIADAMAAIAiAAQAJABAGgBQAHgBALgGQAZgOAHgWQAEgMgDgNQgDgNgKgHQgHgGgRgFQgPgEgHgEIABgHIACgHQACgFAAgMQAAgSgBgJIgCgLQgFgQgLgNQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBAEAEAFIAGAIQABAEAAAIIAEAJIABAKIgBALIABAHQAAAEgBADIgEAJQgBAFABAKIAAAAQgBAFgEAJIgXAwQgFALgFAFQgFAFgJAEQAQghAJg3QALhUAJgoQAMgwAEgXQAJgqgDgfIAjgFQgGAFgEAHQAHAIATgFIATgFQALADALAAIANgBQAGgBACgEQgCgCgGgBIgGgBQAigHAjgCQAWgBAPACQABADADADQAEAEAHAEQAVALALABIAMABQAPABAQAHQAFACACgBQACgCABgGQADgDAAgCQABgCgCgDQgGgKgJgHQADgDgBgGQgBgFgDgDIgQgMIgJgHIgHgBIgKAAIgjgBQA9gSA9gZQAOgFAGAGQAHAGABARQACAfgNAlQgSAxgjAiQghAfgoAMQgcAHgOAFQgYAIgNARQgTAXgJAvQgKA1ACBRIAECHQAAA4gHBuQgDA3AEAeQAEAkATA9IAaBUIgKANQgFAIgKAGIgSAJIglAVQgWAMgRAEQgIACgLAAQgQAAgVgEgAD1l5QATAAAOgCQANgBAAgCQAAgBgGgCIgHgBIgEAAIgdgBIgJAAIgJAAIAGABIgGAAIAAAAIAAgBIgBgBIgBgCIgDgBIAAAAIgDABIgBAAIgCgBIAAAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAgBAAIgCACIAAABIAAABQgNACAAACQAAACAOABIAHABIABAAIABAAIAYABgAi+mCIgIAAQgNACAAACQAAACANABQAOACATAAQAUAAANgCQAJAAADgCIACgBQAAgBgHgCIgHgBIgEAAIgZgBIgEAAIgJAAIgQABgAhMhMQgRgOgCgRQAAgJAFgLQAKgVAkgVIAAAzIACAIIAHARIANATQAHAJAFABIADAGIgEAAIgLABQgeAAgYgTgABSg+IgNgBIAEgDQAHgHAIgQIARgjQAHgPACgJQAHAEAJACQATAGAGAHQANANgFATQgEARgRAKQgMAGgRACIgNAAIgSAAgAFwmhIgDgCIgDgBIgFgBIgCgBIgBgCIAGACIAIACIAIACIgFABIgDAAg");
	this.shape_28.setTransform(445.0133,339.5545);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AEzYDQgOgBgIgJQgIgJgHgYIgWhGQgHAIgKAIQgLAJgbAQQguAbgcADQgTADgigHQglgGgSgOQgQgNgUglQgTAWgaAOQgJAFgfALIgVAGQgFABgTAAQggAAgQgCQg7gIgtgmIggBHQgFALgFABQgFABgHgKQhyibhDhwQhdibg1iWQgKgcAAgSQAAgQAKgdIBIjOQAHgUACgLQAEgSAAgPQgBgZgPgcIgcgtQgkg7gIhaQgIhNAMhaQARiCAxhpQAzhxBLg5QAQgNAjgVQAigVARgNQAQgOAcgbQAfggAMgKQAcgYAwgfIAxgeIg0jjQgXhlgGgnQgJg7gGhkIgjn4QgBgSAGgFQAFgFAPAAQCdADBOAFQCCAJBmAWQAuALAVAPQAjAbAPA5QAaBoguCTQgLAighBWQgdBMgNAtQgRA+gZCpQgRB3gYBMQAFAAABAFQAAADgCAFQgEAEgEACQAXAOAaAOQAwAYBhAsQAxAZAdAeQARATAgAuIBVCAQAtBCAUAkQAhA7AQA5QAXBQgDBgQgEBXgYBYQgHAYAEALQADAJAOAJQAiAVASArQAQAkABA1QACBLgeBkQgRA5gkBxQgGAYgOBIQgMA9gKAiQgYBPgwBKQgmA6g8BAQgbAegTAOQgaARgWAAIgFAAgAEBV8QAFAEgGAIIgCACIAUBDQAGAWAHAIQAHAIAMACQAUAEAYgOQAQgKAXgXQBFhFAshGQA2hVAXhdQAHgZAIguIANhGIA2itQAghoAAhKQgBg0gPgkQgRgogogdQgPgLgCgJQgDgLAHgXQAghlgDhwQgEh0gohbQgQglgdgrIgzhMQgthHgYgiQgog7glggQgjgeg6gZQhBgbgggQQgfgPgegVIgCAGIABgGQgRgMgRgNIgBgBQgKgEgEgEQgFgDgFgIIgDgEIgXgWIgEgDQgPgKgGgHIgqAAIgIABQhGAkgpAYQgBAGgDAEIgBgHIgEADQhDAogyAsQg+A7ghAaQgQAMgqAbQglAYgUARQhBA4gtBmQgpBdgSB0QgOBaAGBOQAIBbAiA7QAKARAVAhQARAeABAcQAAARgFAUQgDANgHAWIhJDQQgIAXAAANQgBASAMAgQB5EwC2DiIAcAjIAkhMIABgDQAWgwANggQAjhbAPhRQAHgpAFg1IAGhgIAOkPQACgagBgOQgBgXgHgPQgGgOgMgLQgHgHgPgLQhfg/gvgoQhNhAgxhJQgLgQAAgNQABgNAMgGQAJgFAMACQA+AJCKBIQAyAaArAQIAPAAQAqgBAgAKQALADAFAGQADAEABAFQAAADgCADQAgDHA/CzIABAAQANgdAKgqQAGgaAJg0IAkjeIAjgGIAEgBIACAAIAPgDIADgBIACAAIAggGIACgCQACgCAFABIAEAAQBygZBvgqQAcgLAKARQAGALgBAVQgDAngOAkQgNAjgWAbQgnAwg7ARIglAKQgUAIgNAPQgYAdgGBEQgGA4AFBwQAEBxgFA2IgGA7QgEAiACAYQACAWAFAaIANAuIAhBwQADgBADAAIABAAgAgNUPQADABABADQABAGAAAMIADAOQAFAYgGANIgEAHQAEAFgDAJIgHAOQgEAMAPAVQAPAVAJAHQAQANAiAGQAjAGAVgEQARgEAWgMIAlgVIASgJQAKgGAFgIIAKgNIgahUQgTg9gEgkQgEgeADg3QAHhuAAg4IgEiIQgChRAKg1QAJgvATgXQANgRAYgIQAOgFAcgHQAogMAhgfQAjgiASgxQANglgCgfQgBgRgHgGQgGgGgOAFQg9AZg9ASIAjABIAKAAIAHABIAJAHIAQAMQADADABAFQABAGgDADQAJAHAGAKQACADgBACQAAACgDADQgBAGgCACQgCABgFgCQgQgHgPgBIgMgBQgLgBgVgLQgHgEgEgEQgDgDgBgDQgQgCgVABQgjACgiAHIAGAAQAFACADACQgCAEgGABIgNABQgLAAgLgEIgTAGQgTAFgHgIQAEgHAGgFIgjAFQADAfgJAqQgEAXgMAwQgJAogLBUQgJA2gQAiQAJgEAFgFQAFgFAFgLIAXgwQAEgJABgFIAAAAQgBgKABgFIAEgJQABgDAAgEIgBgHIABgLIgBgKIgEgJQAAgIgBgEIgGgIQgEgFABgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQALANAFAQIACALQABAJAAASQAAAMgCAFIgCAHIgBAHQAHADAPAFQARAFAHAGQAKAHADANQADANgEAMQgHAWgZAOQgLAGgHABQgGABgJgBIgiAAQgNAAgIgEIgDACIgGACIgDAEIgBgDQgMAFgLAAQgHgBgGgDQgNAHgZgGQgdgGgPgLQgXgQgDgWQgDgWAQgUQAKgOAYgPQAIgFAEgBIABAAIAAgKIABgOIACgIQACgGAAgMIAAgxIABgHQACgFAEACQADAIAAATIAAAkIgBASIgDAKIgBATIAAAkIABAUIACALQAEAMAFAHQAGALATASQAFAFADABIAJABQAIAAAIgDQhBiwgdjJIgJACIgDAAQgVAAg2gGQgkgDgaABQAFAEgFAGIgKAFQgLAEgKAJQgKAJgGAAQgDAAgFgCIgJgDIgIAAQgEAAgBgEIABgFQgMABgKgGIAUgQIANgKQAGgFAJgDIAHgCIAMgEIATgJQAIgCAPABIAEAAQgXgJgYgMQiShKgfgLQgtgPgWAVQAwBTBSBGQAmAgBzBOQAQALAHAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gMDMQgGBigJA2QgOBTgkBfQgMAhgXAyQAEABAFAFQAsAmBBADQA2ADAygVQApgTAJgdIgCgBQAAgFAFgLIAEgJQABgGAAgLIgBgsQAAgQAGgFQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAIABAAgAh8MDQgFALAAAJQACARARAOQAcAWAlgEIAEAAIgDgGQgFgBgHgJIgNgTIgHgRIgCgIIAAgzQgkAUgKAWgABHMGIgRAjQgIAQgHAHIgEADIANABQAUABALgBQARgCAMgGQARgKAEgRQAFgTgNgNQgGgHgTgGQgKgDgGgDQgCAJgHAPgAFBHcIACABIAFABIADABIADACQADABAFgCIgIgCIgIgCIgGgCIABACgAgXotQAKACANAMIANAOIACACQALAGAFAEIAMAQIAIAKIAKAIIAKAGQALAEAFAEQAIAGADgBIAEgCIAojnQAXiAALgvQAWhgAchCIAcg/QARglAHgbQAPg3gBhYQAAhDgKglQgLgngWgRQgSgNgkgHQj1gzj6AKQAMEHAXEiIAKBhQAKBLAaBvIAsC4IACAQIAPgRQAHgHAGgFIAOgGIAcgOQANgGAWgCQAOgHAHgCQAJgDAHAAIAIABgAh8oEQgTAKgKAJIAxgdIgUAKgAC5IIIgCgDIgBAAIAAAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAgBQAAAAAAgBIAAgBIAAgBIACgCQAAgBABAAQAAAAAAAAQABAAAAAAQAAAAABAAIAAAAIACABIABAAIADgBIAAAAIADABIABACIABABIgBABIABAAIAAACIgBACIAAAAIAAABIgBABIgBAAIAAABIgDABIgBAAIgBAAg");
	this.shape_29.setTransform(448.4312,249.6845);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#000000").ss(1,1,1).p("ADFgeQAEgBAEAAQARAAAMAHQACABACABQAEADADAEQAGAHABAIAD8ABQgBANgNAJQgNAJgUAAQgTAAgOgJQgCgCgBAAQgKgJAAgLAj7AAQABgKAIgIQACgCADgDQADgCAEgCQAIgDAJgBQAEgBAFAAQACAAABAAQAPABALAGQACACACAAQAEADADAEQAGAHAAAJAieABQAAAEgBAEQgDAIgJAHQgOAJgTAAQgUAAgNgJQgDgDgCgBQgIgIgBgK");
	this.shape_30.setTransform(448.675,300.75);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.lf(["#FFFFFF","#000000"],[0,1],49.1,-29.8,-124.8,107.7).s().p("AE3QHIgFgBQgMgCgHgIQgHgIgGgWIgUhDIACgCQAGgIgFgEIgGABIAAAAIgihwIgNguQgFgagCgWQgCgYAEgiIAGg7QAFg2gEhxQgFhwAGg4QAGhEAYgdQANgPAUgIIAlgKQA7gRAngwQAWgbANgiQAOgkADgnQABgVgGgLQgHgMgPACQgHABgJADQhvAqhxAZIgFAAIgBAAIgEAAIgCABIgBACIggAGIgDAAIgCABIgQADIgCAAIgEABIgjAGIgkDdIgIAwIgHAeQgKAqgNAdIAAABIgDgJQg+iwgejBQABgDAAgDQgBgFgDgEQgFgGgLgDQgggKgqABIgCAAIgNAAIgBAAQgqgQgygaQiKhIg+gJIgKgBQgGABgFADQgKAFgCALIgBADIABAGQABAKAJANQAxBJBNBAQAvAnBfA/QAPALAHAHQAMALAGAOQAEAKACAMIACAQQABAOgCAaIgOEPIgDA7IgDAeIAAAHIgBAGIgGA6IgDATIgCALQgKA2gTA6IgOApIgHATQgNAggWAwIgBADIgkBMIgEgFIgYgeQi2jih5kwQgMggABgSQAAgNAIgXIBJjQQAHgWADgNQAFgUAAgRQgBgcgRgeQgVgggKgRQgig7gIhbQgGhOAOhaQASh0ApheQAthmBBg4QAUgRAlgYQAqgbAQgMQAhgaA+g7QAxgrBCgoIACgBIABgBIADgBIABAGQADgEABgGQApgYBGgkIAGgBIACAAIAjAAIAHAAQAGAHAPAKIAEADIAYAWIACAEQAFAIAFADQAEAEAKAEIACABIAhAZIgBAGIABgCIABgDQAeAUAfAPQAgAQBBAbQA6AZAjAeQAlAgAoA7QAYAiAtBHIAzBMQAQAYAMAWIAMAYIAFALIAFANIANAiQAXBJADBXQADBwggBlQgHAXADAKQACAJAPALQAoAdARAoQAIATAEAZIADAWIABAWIgBAZIgMBVIgGAWIgKAlIgBADIgCAGIg2CtIgNBGIgBAIIgCAGQgGAkgGAVIgGAZQgYBQgvBJQgsBGhFBFQgXAXgQAKQgTALgRAAIgDAAg");
	this.shape_31.setTransform(448.149,298.6788);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.rf(["#FF0000","#000000"],[0,1],28,-32.1,0,28,-32.1,94.3).s().p("ABiISIgHgEQgFgDgLgFIgKgFIgKgJIgIgKIgMgQQgFgEgLgGIgCgCIgOgOQgMgLgKgDQgGgBgGABIgMACIgUAJQgXACgNAGIgcAOIgOAGQgGAFgHAIIgOAQIgBgHIgCgIIgsi5QgahvgKhKIgKhhQgXkigMkHIAUgBIA6gBIE0AZQA3AHA2AMQAkAGASANQAGAFAFAFIABACIADAFIADAEQAJAOAGAVQAKAlAABDQABA/gHAuQgDATgFAPQgFAUgLAbIgIASIgcA/QgcBBgWBfQgLAvgXCAIgoDnIgEACIgEgBg");
	this.shape_32.setTransform(447.7017,149.55);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AjtAYIgFgEQgIgIgBgKIAAgCQABgKAIgIIAFgEIAHgFQAIgDAJgBIAJgBIADAAQAPABALAGIAEADIAHAGQAGAHAAAJIAAABIgBAIQgDAIgJAHQgOAJgTAAQgUAAgNgJgACsAXIgDgDQgKgIAAgLIAAgBQAAgHAEgFQACgEAEgDIAAAAQAAABABAAQAAAAABABQAAAAABAAQABAAABAAQAGAAADgCIABAAIACAAIAEgCQAAAAAAgBQABAAAAAAQAAAAABAAQAAAAAAAAIADgDIABgDIAAAAIABgBIAAgBIAIgBQARAAAMAHIAEADIAHAFQAGAIABAIIAAABQgBANgNAJQgNAJgUAAQgTAAgOgJg");
	this.shape_33.setTransform(448.675,300.75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFCC99").s().p("ABnJIQgigGgQgNQgJgHgQgVQgPgVAEgMIAHgOQADgJgEgEIAEgIQAGgNgFgYIgDgOQAAgMgBgGQgBgDgDgBQgCgBgDACIAAABQgGAFAAAQIABAsQAAALgBAGIgEAJQgFALAAAFIACABQgIAdgpATQguATgwAAIgKgBQhBgDgsgmQgFgFgDgBQAWgyAMghQAkhfAOhTQAJg2AGhiQAMjLACh7IAAgbQgBgPgEgKQgFgPgMgMQgHgIgQgLQhzhOgmggQhShGgwhTQAMgLASgBQAQgBAVAHQAfALCSBKIAvAWIgEgBIgEAAIgJAAIgKABIgTAJIgMAEIgHACQgJADgGAGIgNAJIgUAQQAHAFAIAAIAHAAIgBAFQABAEAEAAIAIAAIAJADIAFACIADAAQAGAAAKgJQAKgJALgEIAKgFQAFgGgEgEIANAAQAVAAAbACQAxAFAWABIABAAIADAAIADAAIACAAIAGgBIABAAIAEAZIAEAZIBPEwIAHAWQgJADgIAAIgFAAIgEgBQgDgBgFgFQgSgSgGgLQgFgHgEgMIgCgLIgBgUIAAgkIABgTIADgKIABgSIAAgkQAAgTgDgIQgDgCgCAEIgBABIgBAHIAAAxQAAAMgCAGIgCAIIgBAOIAAAKIgBAAQgEABgIAFQgYAPgKAOQgQAUADAWQADAWAXAQQAPALAdAGIAQADQALAAAHgCIAEgCQAFADAGABIABAAQAIAAAKgCIABAAIAFgCIABACIADgEIAGgCIAEgBQAHADANAAIAiAAIADABIAMgBQAHgBALgGQAZgOAHgWQAEgMgDgNQgDgNgKgHQgHgGgRgFIgWgIIABgHIACgHQACgFAAgMQAAgSgBgJIgCgLQgFgQgLgNQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAABIgBABIgBADQgBAEAEAFIAGAIQABAEAAAIIAEAJIABAKIgBALIABAHQAAAEgBADIgEAJQgBAFABAKIAAAAQgBAFgEAJIgXAwQgFALgFAFQgFAFgJAEIADgFQAOghAIgyQAHg1AGgjIACgNIAFgXQAMgwAEgXQAJgqgDgfIAbgEIAIgBQgGAFgEAHQADAEAGABQAHABAKgDIAQgEIADgBQAJACAJABIAEAAIAHAAQgEAAgDADQgDABgCADIAAABQgBADACACQgDADgCADQgEAGgBAHIAAACQABALAJAIIAEADQANAJAUAAQATAAAOgJQANgJAAgNIAAgCQAAgJgGgHIgHgGIgEgCQgNgHgQAAIgIAAIAAAAIgBgCIgBgCIgDgBIAAABIgCAAIADgDQgDgCgFgBIgGgBQAigHAjgCIAMAAQAOgBALACQABADADADQAEAEAHAEQAVALALABIAMABQAPABAQAHIABAAQAEACACgBQACgCABgGQADgDAAgCQABgCgCgDQgGgKgJgHQADgDgBgGQgBgFgDgDIgQgMIgJgHIgHgBIgKAAIgegBIgCAAIgDAAQA9gSA9gZIAIgCQAIgBAEAEQAHAGABARIABAKQgBAbgLAfIgBAEQgTAughAhQghAfgoAMQgcAHgOAFQgYAIgNARQgTAXgJAvQgKA1ACBRIAAAIIACA5IAAAFIABAfIABAiIAAArIgDA9IgEA+QgDA3AEAeIACANQAFAiAQAyIAaBUIgKANQgFAIgKAGIgSAJIglAVQgWAMgRAEQgKACgNAAQgOgBgTgDgAiumeQgJABgHADIgIAEIgFAFQgIAIAAAKIAAADQABAKAIAIIAEADQAOAKATAAQAUAAANgKQAJgGADgIIACgIIAAgCQgBgJgGgHIgHgHIgEgCQgLgGgOgBIgEAAIgJABgAgZg5QgcgBgXgSQgRgOgCgRQAAgJAFgLQAJgTAegSIAHgFIAAAzIACAIIAHARIANATQAHAJAFABIADAGIgEAAIgKABIgEAAgABSg+IgNgBIAEgDQAHgHAIgQIARgjQAGgNACgIIABgDIAQAGQATAGAGAHQANANgFATQgEARgRAKQgMAGgRACIgRAAIgOAAgAFwmhIgDgCIAFACIAAAAIgCAAg");
	this.shape_34.setTransform(444.725,339.0688);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AEwYDQgOgBgJgJQgHgJgIgYIgUhAIgLAKQgLAJgcAQQgtAbgcADIgQABQgSAAgagFQglgGgSgOQgQgMgSghQgRATgYAMQgJAFgfALIgVAGQgEABgQAAIgDAAIgHAAIgSAAQgTAAgLgCQg4gHgrgiIgfBCQgEALgFABQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAgBgBAAIgCABQgFABgIgKQhyibhDhwQhcibg2iWQgKgcAAgSQAAgQAKgdIBIjOQAHgUADgLQAEgSAAgPQgBgZgPgcIgdgtQgjg7gJhaQgIhNAMhaQASiCAwhpQAzhxBLg5QAQgNAjgVQAigVARgNQARgOAbgbQAgggAMgKQAbgYAxgfIAxgeIg1jjQgWhlgGgnQgJg7gHhkIgin4QgBgSAGgFQAFgFAPAAIAEAAIADAAQCEACBMAFIAbABQCBAJBmAWQAvALAVAPQAjAbAOA5QAbBogvCTQgLAighBWQgdBMgMAtQgSA+gYCpQgSB3gXBMQAEAAABAFQABADgDAFQgDAEgEACQAWAOAbAOQAwAYBhAsQAxAZAcAeQASATAfAuIBWCAQAsBCAUAkQAhA7AQA5QAXBQgDBgQgDBXgZBYQgHAYAEALQAEAJAOAJQAiAVASArQAQAkABA1QACBLgfBkQgQA5gkBxQgGAYgOBIQgNA9gKAiQgYBPgwBKQgmA6g7BAQgbAegUAOQgbASgYgBIAAAAIgBAAIgEAAIgDAAgAEDWIIgBACIAUBDQAGAWAHAIQAGAIAMACIAGABQASABAUgMQARgKAXgXQBEhFAshGQAvhJAYhQIAHgZQAFgVAHgkIABgGIABgIIAOhGIA2itIACgGIAAgDIALglIAFgWIANhVIAAgZIgBgWIgCgWQgFgZgIgTQgRgogogdQgOgLgDgJQgDgLAHgXQAghlgDhwQgChXgXhJIgNgiIgFgNIgFgLIgNgYQgMgVgPgYIgzhMQgthHgYgiQgpg7gkggQgkgeg5gZQhCgbgggQQgfgPgdgUIgCADIAAACIABgGIgigZIgCgBQgJgEgFgEQgEgDgFgIIgDgEIgXgWIgFgDQgOgKgGgHIgHAAIgjAAIgCAAIgGABQhHAkgoAYQgBAGgDAEIgCgGIgDABIgBABIgCABQhBAogyArQg+A7ghAaQgPAMgrAbQglAYgUARQhAA4gtBmQgpBdgTB0QgOBaAHBOQAHBbAjA7QAJARAWAhQAQAeABAcQABARgFAUQgDANgIAWIhIDQQgIAXgBANQAAASAMAgQB4EwC2DiIAYAeIAFAFIAjhMIACgDQAVgwANggIAIgTIAOgpQASg6AKg2IACgLIADgTIAHg6IAAgGIABgHIACgeIADg7IAPkPQABgagBgOIgBgQQgCgMgEgKQgGgOgMgLQgIgHgPgLQhfg/gvgoQhMhAgxhJQgJgNgCgKIAAgGIAAgDQACgLAKgFQAFgDAHgBIAKABQA+AJCJBIQAzAaAqAQIAAAAIAOAAIABAAQAqgBAgAKQAMADAFAGQADAEAAAFQABADgCADQAeDCA+CwIADAJIABgBQANgdAKgqIAGgeIAIgwIAljeIAjgGIADgBIACAAIAQgDIADgBIACAAIAggGIABgCIACgBIAFAAIABAAIAEAAQBxgZBwgqQAIgDAHgBQAQgCAHAMQAFALgBAVQgCAngOAkQgNAjgWAbQgnAwg7ARIglAKQgVAIgMAPQgYAdgHBEQgFA4AEBwQAEBxgFA2IgGA7QgDAiABAYQACAWAGAaIANAuIAhBwIABAAIAGgBQAFAEgHAIgAgJUPQACABABADQACAGAAAMIACAOQAFAYgGANIgDAIQAEAEgEAJIgHAOQgDAMAOAVQAPAVAJAHQARANAiAGQASADAPABQANAAAKgCQARgEAVgMIAlgVIATgJQAKgGAFgIIAJgNIgZhUQgQgygGgiIgCgNQgEgeADg3IAEg+IADg9IABgrIgCgiIgBgfIAAgFIgBg6IgBgIQgChRAKg1QAKgvASgXQAOgRAYgIQAOgFAcgHQAogMAggfQAighASguIACgEQALgfAAgbIAAgKQgBgRgHgGQgFgEgIABIgIACQg8AZg9ASIADAAIABAAIAeABIAKAAIAIABIAJAHIAPAMQAEADABAFQABAGgDADQAJAHAFAKQACADAAACQAAACgDADQgBAGgDACQgCABgEgCIgBAAQgPgHgQgBIgMgBQgKgBgVgLQgHgEgEgEQgDgDgBgDQgMgCgOABIgLAAQgjACgiAHIAGABQAFABACACIgCADIABAAIAAgBIADABIACACIAAACIAAAAIAAACIgBAAIAAABIgBADIgDACQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAABIgEABIgCABIgBAAQgDACgGAAQgBAAgBAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIAAAAQgDgCACgDIAAgBQABgDADgBQADgDAEAAIgHAAIgDAAQgJgBgJgCIgEABIgPAEQgLADgGgBQgGgBgDgEQAEgHAFgFIgIABIgaAEQADAfgJAqQgFAXgMAwIgEAXIgCANQgGAjgHA1QgIAygOAhIgDAFQAJgEAFgFQAFgFAFgLIAXgwQAEgJAAgFIAAAAQgBgKACgFIAEgJQABgDgBgEIAAgHIABgLIgBgKIgEgJQAAgIgCgEIgFgIQgEgFAAgEIABgDIABgBQABgBAAAAQABAAAAAAQABAAAAAAQABAAABAAQALANAEAQIACALQACAJAAASQAAAMgCAFIgDAHIgBAHIAWAIQARAFAIAGQAJAHADANQADANgEAMQgHAWgYAOQgLAGgHABIgMABIgDgBIgiAAQgNAAgIgDIgDABIgGACIgDAEIgBgCIgGACIAAAAQgJACgIAAIgBAAQgHgBgFgDIgDACQgIACgLAAIgQgDQgdgGgPgLQgYgQgDgWQgDgWAQgUQALgOAXgPQAIgFAEgBIABAAIAAgKIABgOIADgIQACgGAAgMIgBgxIABgHIABgBQACgEADACQAEAIAAATIgBAkIgBASIgDAKIgBATIAAAkIABAUIADALQADAMAFAHQAHALATASQAFAFADABIAEABIAFAAQAHAAAJgDIgHgWIhQkwIgEgZIgEgZIAAAAIgGABIgDAAIgDAAIgCAAIgCAAQgVgBgygFQgbgCgUAAIgOAAQAEAEgFAGIgJAFQgLAEgLAJQgJAJgGAAIgEAAIgFgCIgJgDIgHAAQgFAAgBgEIACgFIgHAAQgJAAgHgFIAVgQIANgJQAFgGAKgDIAGgCIAMgEIAUgJIAKgBIAIAAIAEAAIAEABIgugWQiShKgfgLQgVgHgQABQgTABgLALQAvBTBTBGQAmAgBzBOQAPALAIAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gNDMQgGBigJA2QgOBTgjBfQgNAhgWAyQADABAGAFQAsAmBBADIAJABQAxAAAtgTQAqgTAJgdIgDgBQABgFAEgLIAEgJQACgGAAgLIgBgsQAAgQAFgFIABgBIAEgBIABAAgAqrOsIABADIgDgHQgKgcAAgSQAAASAMAggAhRLeQgeASgKATQgFALABAJQABARASAOQAWASAcABIAPgBIAEAAIgDgGQgGgBgHgJIgNgTIgGgRIgCgIIAAgzIgHAFgABTLxQgDAIgGANIgRAjQgIAQgGAHIgEADIAMABIAPAAIAQAAQARgCAMgGQARgKAFgRQAFgTgNgNQgHgHgSgGIgRgGIAAADgADDHiIACAAIABgBIgDABgAFaHgIgIgCIgIgCIgHgCIACACIABABIAFABIACAAIABABIAAAAIABAAIADACIABAAIAHgBgAqxE8IADAdIgCgRQgCgWgBgYQAAASACAQgAgUotQALACALAMIAOAOIADACQALAGAEAEIANAQIAIAKIAKAJIAKAFQALAEAEAEIAHAEIAFABIAEgCIAnjnQAXiAALgvQAXhgAchCIAcg/IAIgSQAKgaAGgUQAEgQADgSQAHguAAg/QAAhDgLglQgGgVgIgOIgDgEIgDgFIgCgCQgFgGgGgEQgRgNgkgHQg3gLg2gIIk0gYIg7ABIgTABQALEHAYEiIAKBhQAJBLAbBvIAsC4IABAJIABAHIAOgRQAHgHAGgFIAPgGIAbgOQAOgGAWgCIAVgJIAMgDIAEAAIAHABg");
	this.shape_35.setTransform(447.7812,249.1875);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#000000").ss(1,1,1).p("AieABQAAABAAABQAAAFgBAFQgDALgJAJQgOANgTAAQgUAAgNgNQgNgNgBgSIAAgCQAAAAAAAAQABgTANgNQADgDAEgDQAIgFAJgCQAEAAAFAAQACAAABAAQAPAAALAKQACABACACQAEAEADAFQAGAKAAANgAC6gpQAFgCAFgCQAFAAAEAAQARAAAMAKQACABACACQAEAEADAFQAHAKAAANIAAACQgBASgNANQgNANgUAAQgTAAgOgNQgMgNgBgSIAAgBQAAAAAAgBIAAAAQAAgTANgN");
	this.shape_36.setTransform(449.675,301.25);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("ACsAhQgMgNgBgSIAAAAIAAgCIAAAAQAAgTANgNIACAAIAMgBIADgBQADgBABgDQgCgCgFgBQAFgDAFAAIAJgBQARAAAMAKIAEADIAHAJQAHAKAAANIAAACQgBASgNANQgNAOgUAAQgTAAgOgOgAjtAhQgNgNgBgSIAAgCIAAAAQABgTANgNIAHgGQAIgFAJgBIAJgBIADAAQAPABALAJIAEADIAHAJQAGAKAAANIAAACIAAABIgBAJQgDAMgJAJQgOAOgTAAQgUAAgNgOg");
	this.shape_37.setTransform(449.675,301.25);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.lf(["#FFFFFF","#000000"],[0,1],117.6,-41.6,-56.3,96).s().p("AAFFIQgLggABgTQAAASAJAcIACAHIgBgCgAAAknIgCgiIABARIADAoIABALIgDgig");
	this.shape_38.setTransform(379.8365,310.95);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFCC99").s().p("ACIJMQgOgBgTgDQgigGgQgNQgJgHgQgVQgPgVAEgMIAHgOQADgJgEgEIAEgIQAGgNgFgYIgDgOQAAgMgBgGQgBgDgDgBQgCAAgDABIAAABQgGAFAAAQIABAsQAAALgBAGIgEAJQgFALAAAFIACABQgIAdgpATIgCABIhcASIAAAAIgKgBQhBgDgsgmQgFgFgDgBQAWgyAMghQAkhfAOhTQAJg2AGhiQAMjLACh7IAAgbQgBgPgEgKQgFgPgMgMQgHgIgQgLQhzhOgmggQhShGgwhTIAWgLQAGgBAIAAIAaAFIABAAIABAAIACABIABAAQAfALCSBKIAvAWIgEgBIgEAAIgJAAIgKABIgTAJIgMAEIgHACQgJADgGAGIgNAJIgUAQQAHAFAIAAIAHAAIgBAFQABAEAEAAIAIAAIAJADIAAAAIAFACIABAAIACAAIAAAAQAGAAAKgJQAKgJALgEIAKgFQAFgGgEgEIANAAQAVAAAbACQAxAFAWABIABAAIADAAIADAAIACAAIADAAIAEgBIADAYIABABIAEAZQAcClA1CTIAFAOQgJADgIAAIgFAAIgEgBQgDgBgFgFQgSgSgGgLQgFgHgEgMIgCgLIgBgUIAAgkIABgTIADgKIABgSIAAgkQAAgTgDgIIgBAAIgBgBQgCABgCADIAAAAIgBAHIAAAxQAAAMgCAGIgCAIIgBAOIAAAKIgBAAQgEABgIAFQgYAPgKAOQgQAUADAWQADAWAXAQQAPALAdAGIAJACQAKABAHAAIAIgCIAEgCIABABIAAAAIAFACIAGABIAAAAIACAAIAMgBIAEgBIABAAIADgBIACgBIABACIADgEIAGgCIAEgBQAHADANAAIAiAAIADABQAHAAAFgBQAHgBALgGQAZgOAHgWQAEgMgDgNQgDgNgKgHQgHgGgRgFIgWgIIABgHIACgHQACgFAAgMQAAgSgBgJIgCgLQgFgQgLgNQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAIgCADIAAABQgBAEAEAFIAGAIQABAEAAAIIAEAJIABAKIgBALIABAHQAAAEgBADIgEAJQgBAFABAKIAAAAQgBAFgEAJIgXAwQgFALgFAFQgFAFgJAEIABgBIAEgKIAThIIABgDIAAgCIADgSIAKhGIACgIIAAgFIAFgXQAMgwAEgXQAJgqgDgfIAGgBIAQgCIAFgBIAEgBIAEAAQgGAFgEAHQADAEAGABQAHABAKgDIAQgEIADgBIADABIAMACIADAAIAEAAQgNANgBATIAAABIAAABIAAABQABASANANQANANAUAAQATAAAOgNQANgNAAgSIAAgDQAAgNgGgKIgHgJIgEgEQgNgKgQAAIgJABQgGABgFADIgGgBQAigHAjgCIAMAAQAOAAALABQABADADADQAEAEAHAEQAVALALABIAMABQAPABAQAHIABAAQAEACACgBQACgCABgGQADgDAAgCQABgCgCgDQgGgKgJgHQADgDgBgGQgBgFgDgDIgQgMIgJgHIgHgBIgKAAIgGAAIgYgBIgCAAIgDAAQA9gSA9gZIAIgCQAIgBAEAEQAHAGABARIABAKQgBAbgLAfIAAAAIgBAEQgTAughAhQghAfgoAMQgcAHgOAFQgYAIgNARQgTAXgJAvQgKA1ACBRIAAABIACBAIAAAFIABAXIAAAQIABAaIAAAEIAAABIAAACIAAABIAAAdIAAAGIgBAPIgCAuIgEA1IAAABIAAAEIAAAEQgDA3AEAeIAAABIADAUIASBEIABADIABAFIAaBUIgKANQgFAIgKAGIgSAJIglAVQgWAMgRAEQgIACgLAAIgEAAgAiumsQgJACgHAFIgIAGQgNANAAATIAAABIAAACQABASAMANQAOANATAAQAUAAANgNQAJgJADgMIACgJIAAgCIAAgCQAAgNgHgKIgHgJIgEgEQgLgJgOgBIgEAAIgJABgAgZg5QgcgBgXgSQgRgOgCgRQAAgJAFgLQAJgTAegSIAHgFIAAAzIACAIIAHARIANATQAHAJAFABIADAGIgEAAIgKABIgEAAgABgg+IgLAAIgDAAIgNgBIAEgDQAHgHAIgQIARgjIABgDIAFgMIADgHIAAgBIAAgBIAQAGQATAGAGAHQANANgFATQgEARgRAKQgMAGgRACIgOAAIgDAAgAFwmhIgDgCIgCgBIgBAAIgFgBIgCgBIgBgCIAGACIAIACIAIACIgFABIgDAAg");
	this.shape_39.setTransform(445.713,339.5523);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.lf(["#FFFFFF","#000000"],[0,1],49.1,-29.8,-124.8,107.7).s().p("AE3QHIgFgBQgMgCgHgIQgHgIgGgWIgUhDIACgCQAGgIgFgEIgGABIAAAAIgihwIgNguQgFgagCgWQgCgYAEgiIAGg7QAFg2gEhxQgFhwAGg4QAGhEAYgdQANgPAUgIIAlgKQA7gRAngwQAWgbANgiQAOgkADgnQABgVgGgLQgDgFgFgDIgEgBQgFgCgGABQgGABgIADIgBAAQhvAqhxAZIgFAAIgEAAIgCAAIgBABIgBACIggAGIgDAAIgCABIgQADIgCAAIgEABIgjAGIgkDdIgJAwIgGAeQgKAqgNAdIAAABIgBgCIgGgSIhYlmQABgDAAgDQgBgFgDgEQgFgGgLgDQgggKgqABIgCAAIgNAAIgBAAQgqgQgygaQiKhIg+gJIgBAAIgDgBIgBAAQgGAAgFACIgFACIAAAAIgBAAIgJAJIgDAHIAAACIAAABIAAAAIAAABIAAABIACAJIAHAPIACADQAxBJBNBAQAvAnBfA/QAPALAHAHQAMALAGAOQAEAKACAMIACAQQABAOgCAaIgOEPIgBAKIgCAmIgBAUIgCAVIAAADIAAAEIgBAGIgGA6IgDATIgCALQgKA2gTA6IgMAlIgEAJIgFAOQgNAggWAwIgBADIgkBMIgBgBIgDgEIgHgIIgPgTIgCgCIAAgBQi2jih5kwQgMggABgSQAAgNAIgXIBJjQQAHgWADgNQAFgUAAgRQgBgcgRgeQgVgggKgRQgig7gIhbQgGhOAOhaQASh0ApheQAthmBBg4QAUgRAlgYQAqgbAQgMQAhgaA+g7QAxgrBBgoIACgBIABAAIABgBIADgBIABAGQADgEABgGQApgYBGgkIAGgBIAbAAIAKAAIAHAAQAGAHAPAKIAEADIAYAWIACAEQAFAIAFADQAEAEAKAEIACABIAhAZIgBAGIAAgBIABgBIAAgBIABgCQAeAUAfAPQAgAQBBAbQA6AZAjAeQAlAgAoA7QAYAiAtBHIAzBMIAaArIADAGIAOAbIAGAPIABADIANAiQAXBJADBXQADBwggBlQgHAXADAKQACAJAPALQAoAdARAoIALApIABADIAAACIADAZIABARIgBAZIgNBVIgFAWIgHAcIgGASIg2CtIgNBGIgCAIIgBAGQgHAkgFAVIgHAZQgXBQgvBJQgsBGhFBFQgXAXgQAKQgTALgQAAIgEAAg");
	this.shape_40.setTransform(449.1494,299.1689);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.rf(["#FF0000","#000000"],[0,1],28,-32.1,0,28,-32.1,94.3).s().p("ABiISIgHgEQgFgEgLgEIgKgFIgKgJIgIgKIgMgQQgFgEgLgGIgCgCIgOgOQgMgMgKgCQgFgBgHAAIgMADIgUAJQgXACgNAGIgcAOIgOAGQgGAFgHAHIgOARIgBgDIgBgIIgBgFIgsi4QgahvgKhLIgKhhQgXkhgMkHIAUgBIA6gBQCmAACkAbIBBAMIARADIAFABQAkAHASANQAGAEAFAGIABACIAGAJQAJAOAGAVQAKAlAABDQABA/gHAuQgDASgFAQQgFAUgLAaIgIASIgcA/QgcBBgWBgQgLAvgXCAIgoDnIgEACIAAABIgEgCg");
	this.shape_41.setTransform(448.7031,150.0518);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AEwYDQgOgBgJgJQgHgJgIgYIgUhBIgLALQgLAJgcAQQgtAbgcADIgCAAIgJABIgFAAQgSAAgagFQglgGgSgOQgQgMgSghQgRATgYAMQgJAFgfALIgVAGIgUABIgDAAIgHAAIgTAAIgdgCQg4gHgrgjIgfBDQgEALgFABQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBgBIgCABQgFABgIgKQhyibhDhwQhcibg2iWQgKgcAAgSQAAgQAKgdIBIjOQAHgUADgLQAEgSAAgPQgBgZgPgcIgdgtQgjg7gJhaQgIhNAMhaQASiCAwhpQAzhxBLg5QAQgNAjgVQAigVARgNQARgOAbgbQAgggAMgKQAbgYAxgfIAxgeIg1jjQgWhlgGgnQgJg7gHhkIgin4QgBgSAGgFQAFgFAPAAIADAAIAEAAIACAAIDEAGIAYABIALABIACAAQCBAJBmAWQAvALAVAPQAjAbAOA5QAbBogvCTQgLAighBWQgdBMgMAtQgSA+gYCpQgSB3gXBMQAEAAABAFQABADgDAFQgDAEgEACQAWAOAbAOQAwAYBhAsQAxAZAcAeQASATAfAuIBWCAQAsBCAUAkQAhA7AQA5QAXBQgDBgQgDBXgZBYQgHAYAEALQAEAJAOAJQAiAVASArQAQAkABA1QACBLgfBkQgQA5gkBxQgGAYgOBIQgNA9gKAiQgYBPgwBKQgmA6g7BAQgbAegUAOQgbASgYgBIgBAAIAAAAIgEAAIgDAAgAEDWIIgBACIAUBDQAGAWAHAIQAGAIAMACIAGABQASABAUgMQARgKAXgXQBEhFAshGQAvhJAYhQIAHgZQAFgVAHgkIABgHIABgHIAOhGIA2itIAFgSIAIgdIAFgVIAMhVIABgZIgBgRIgCgaIgBgCIAAgDIgMgoQgRgogogdQgOgLgDgJQgDgLAHgXQAghlgDhwQgChYgYhIIgMgjIgCgDIgGgOIgNgbIgDgGIgagqIgzhMQgthHgYgiQgpg7gkggQgkgeg5gZQhCgbgggQQgfgPgdgUIgBABIgBACIAAABIAAABIABgGIgigZIgCgBQgJgEgFgEQgEgDgFgIIgDgEIgXgWIgFgDQgOgKgGgHIgHAAIgLAAIgaAAIgGABQhHAkgoAYQgBAGgDAEIgCgGIgDABIgBABIAAAAIgCABQhBAogyArQg+A7ghAaQgPAMgrAbQglAYgUARQhAA4gtBmQgpBdgTB0QgOBaAHBOQAHBbAjA7QAJARAWAhQAQAeABAcQABARgFAUQgDANgIAWIhIDQQgIAXgBANQAAASAMAgQB4EwC2DiIABAAIACADIAPATIAGAHIADAEIACACIAjhMIACgDQAVgwANggIAGgOIADgJIANglQASg6AKg2IACgLIADgTIAHg7IAAgFIAAgEIABgDIABgWIABgTIADgmIAAgKIAPkPQABgagBgOIgBgQQgCgMgEgKQgGgOgMgLQgIgHgPgLQhfg/gvgoQhMhAgxhJIgDgEIgHgPIgBgIIAAgBIAAgBIAAgBIAAgBIAAgBIACgHIAJgJIABAAIABgBIAFgCQAFgBAGAAIABAAIADAAIABABQA+AJCJBIQAzAaApAQIABAAIANAAIACAAQAqgBAgAKQAMADAFAGQADAEAAAFQABADgCADIBYFnIAGARIABADIABgBQANgdAKgqIAGgfIAIgvIAljeIAjgGIADgBIACAAIAQgDIADgBIACAAIAggGIABgCIACgBIABgBIAFABIAEAAQBxgZBwgqIABgBQAHgCAHgBQAGgBAFACIADABQAFADAEAFQAFALgBAVQgCAngOAkQgNAjgWAbQgnAwg7ARIglAKQgVAIgMAPQgYAdgHBEQgFA4AEBwQAEBxgFA2IgGA7QgDAiABAYQACAWAGAaIANAuIAhBwIABAAIAGgBQAFAEgHAIgAgJUPQACABABADQACAGAAAMIACAOQAFAYgGANIgDAIQAEAEgEAJIgHAOQgDAMAOAVQAPAVAJAHQARANAiAGQASADAPAAQANABAKgCQARgEAVgMIAlgVIATgJQAKgGAFgIIAJgNIgZhUIgCgFIgBgEIgShDIgDgUIAAgBQgEgeADg3IAAgEIABgEIAAgBIADg1IACguIABgPIAAgGIABgdIAAgBIAAgCIAAgCIAAgDIgBgaIgBgQIgBgXIAAgFIgChBIAAgBQgChRAKg1QAKgvASgXQAOgRAYgIQAOgFAcgHQAogMAggfQAighASguIABgEIABAAQALgfAAgcIAAgJQgBgRgHgGQgFgEgIABIgIACQg8AZg9ASIACAAIACAAIAZAAIAFABIAKAAIAIABIAJAHIAPAMQAEADABAFQABAGgDADQAJAHAFAKQACADAAACQAAACgDADQgBAGgDACQgCABgEgCIgBAAQgPgHgQgBIgMgBQgKgBgVgLQgHgEgEgEQgDgDgBgDQgMgCgOAAIgLABQgjACgiAHIAGABQAFABACACQgBACgDACIgDABIgMABIgCAAIgDAAIgEgBIgLgCIgDAAIgEAAIgPAFQgLADgGgBQgGgBgDgEQAEgHAFgFIgEAAIgEABIgFABIgQACIgFABQADAfgJAqQgFAXgMAwIgEAXIgBAFIgCAIIgKBGIgCASIgBACIAAADIgTBIIgFAJIAAACQAJgEAFgFQAFgFAFgLIAXgwQAEgJAAgFIAAAAQgBgKACgFIAEgJQABgDgBgEIAAgHIABgLIgBgKIgEgJQAAgIgCgEIgFgIQgEgFAAgEIAAgBIACgDQABgBAAAAQABAAAAAAQABAAAAAAQABAAABAAQALANAEAQIACALQACAJAAASQAAAMgCAFIgDAHIgBAHIAWAIQARAFAIAGQAJAHADANQADANgEAMQgHAWgYAOQgLAGgHABQgGABgGgBIgDAAIgiAAQgNAAgIgDIgDABIgGACIgDAEIgBgCIgCAAIgEABIgBABIgDABIgMABIgBAAIgBAAIgGgCIgEgBIgBgBIgBAAIgEACIgIABQgIABgKgBIgIgCQgdgGgPgLQgYgQgDgWQgDgWAQgUQALgOAXgPQAIgFAEgBIABAAIAAgKIABgOIADgIQACgGAAgMIgBgxIABgHIAAgBQACgDACAAIACAAIAAABQAEAIAAATIgBAkIgBASIgDAKIgBATIAAAkIABAUIADALQADAMAFAHQAHALATASQAFAFADABIAEABIAFAAQAHAAAJgDIgFgOQg1iTgdimIgEgYIAAgCIgEgXIgEAAIgDABIgCAAIgDAAIgDAAIgBAAQgWgBgxgFQgbgCgUAAIgOAAQAEAEgFAGIgJAFQgLAEgLAJQgJAJgGAAIgBAAIgCAAIgBgBIgEgBIgBAAIgJgDIgIAAQgEAAgBgEIACgFIgHAAQgJgBgHgEIAVgQIANgJQAFgGAKgDIAGgCIAMgEIAUgJIAKgBIAIAAIAEAAIAEABIgugWQiShKgfgLIgCAAIgBgBIgCAAIgBgBIgagEQgIAAgGABIgVALQAvBTBTBGQAmAgBzBOQAPALAIAIQAMAMAFAPQAEAKABAPIAAAbQgCB7gNDMQgGBigJA2QgOBTgjBfQgNAhgWAyQADABAGAFQAsAmBBADIAJAAIABAAIBcgSIABAAQAqgTAJgdIgDgBQABgFAEgLIAEgJQACgGAAgLIgBgsQAAgQAFgFIABgBQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIABAAgAqrOsIABADIgDgHQgKgcAAgSQAAASAMAggAhSLdQgdATgKATQgFALABAJQABARASAOQAWASAcABIAPgBIAEAAIgDgGQgGgBgHgJIgNgTIgGgRIgCgIIAAgzIgIAEgABTLvIAAAAIgCAIIgFAMIgCADIgRAjQgIAQgGAHIgEADIAMABIAEAAIAKAAIARAAQARgCAMgGQARgKAFgRQAFgTgNgNQgHgHgSgGIgRgGgAFFHcIABABIAFABIABAAIACABIAEACQACABAGgCIgIgCIgIgCIgHgCIACACgAqxE8IAEAjIgCgLIgDgoIgBgSIACAigAgUotQALACALAMIAOAOIADACQALAGAEAEIANAQIAIAKIAKAJIAKAFQALAEAEAEIAHAEIAFABIAEgCIAnjnQAXiAALgvQAXhgAchCIAcg/IAHgSQALgaAGgUQAEgQADgSQAHguAAg/QAAhDgLglQgGgVgJgPIgGgIIgBgCQgFgGgGgEQgRgNgkgHIgGgBIgRgDIhBgMQijgbinAAIg6ABIgTABQALEHAYEiIAKBhQAJBLAbBvIAsC4IAAAFIACAHIAAAEIAOgRQAHgHAGgFIAPgGIAbgOQAOgGAWgCIAVgJIAMgDIADAAIAIABg");
	this.shape_42.setTransform(448.7812,249.682);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11,p:{y:248.6845}},{t:this.shape_10,p:{y:338.5545,x:444.5133}},{t:this.shape_9},{t:this.shape_8,p:{y:149.0456}},{t:this.shape_7,p:{y:298.1694,x:447.9494}},{t:this.shape_6,p:{y:300.25,x:448.475}}]},10).to({state:[{t:this.shape_11,p:{y:247.6845}},{t:this.shape_10,p:{y:337.5545,x:444.5133}},{t:this.shape_12,p:{x:448.475}},{t:this.shape_8,p:{y:148.0456}},{t:this.shape_7,p:{y:297.1694,x:447.9494}},{t:this.shape_6,p:{y:299.25,x:448.475}}]},1).to({state:[{t:this.shape_14},{t:this.shape_10,p:{y:337.5545,x:444.0133}},{t:this.shape_12,p:{x:447.975}},{t:this.shape_13},{t:this.shape_7,p:{y:297.1694,x:447.4494}},{t:this.shape_6,p:{y:299.25,x:447.975}}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_1},{t:this.shape_4},{t:this.shape}]},6).to({state:[{t:this.shape_21},{t:this.shape_16},{t:this.shape_15},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18}]},4).to({state:[{t:this.shape_25},{t:this.shape_16},{t:this.shape_15},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22}]},1).to({state:[{t:this.shape_29},{t:this.shape_16},{t:this.shape_15},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_25},{t:this.shape_16},{t:this.shape_15},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22}]},1).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30}]},1).to({state:[{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36}]},1).wait(33));

	// Body
	this.instance_7 = new lib.CachedBmp_1();
	this.instance_7.setTransform(274.05,390.9,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(60));

	// BG
	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#000000").ss(1,1,1).p("EhROAqbMAAAhU1MCidAAA");
	this.shape_43.setTransform(494.1,267.5);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.bf(img.pexelssaguiandrea618833, null, new cjs.Matrix2D(1,0,0,1.372,-1100,-923.4)).s().p("EhRNA6NIAA/kMAAAhU1MCibAAAMAAAB0Zg");
	this.shape_44.setTransform(494.1,368.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43}]}).wait(60));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(453.3,315,561.7,426);
// library properties:
lib.properties = {
	id: 'C3EED686E0264D91A7D61840292FF558',
	width: 960,
	height: 640,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/pexelssaguiandrea618833.jpg", id:"pexelssaguiandrea618833"},
		{src:"images/MolonLabe_HTML5 Canvas_atlas_1.png", id:"MolonLabe_HTML5 Canvas_atlas_1"},
		{src:"sounds/MySong256wav.mp3", id:"MySong256wav"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C3EED686E0264D91A7D61840292FF558'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;